// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: ing.observ.temp.comment
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A comment on an observation. Used for general discussion, questions, or additional context about an observation.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "ing.observ.temp.comment",
    tag = "$type"
)]
pub struct Comment<'a> {
    ///The text content of the comment.
    #[serde(borrow)]
    pub body: CowStr<'a>,
    ///Timestamp when this comment was created.
    pub created_at: Datetime,
    ///Optional reference to another comment this is replying to, for threaded discussions.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub reply_to: Option<StrongRef<'a>>,
    ///A strong reference (CID + URI) to the observation being commented on.
    #[serde(borrow)]
    pub subject: StrongRef<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CommentGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Comment<'a>,
}

impl<'a> Comment<'a> {
    pub fn uri(uri: impl Into<CowStr<'a>>) -> Result<RecordUri<'a, CommentRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct CommentRecord;
impl XrpcResp for CommentRecord {
    const NSID: &'static str = "ing.observ.temp.comment";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CommentGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<CommentGetRecordOutput<'_>> for Comment<'_> {
    fn from(output: CommentGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Comment<'_> {
    const NSID: &'static str = "ing.observ.temp.comment";
    type Record = CommentRecord;
}

impl Collection for CommentRecord {
    const NSID: &'static str = "ing.observ.temp.comment";
    type Record = CommentRecord;
}

impl<'a> LexiconSchema for Comment<'a> {
    fn nsid() -> &'static str {
        "ing.observ.temp.comment"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_ing_observ_temp_comment()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.body;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("body"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod comment_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Body;
        type CreatedAt;
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Body = Unset;
        type CreatedAt = Unset;
        type Subject = Unset;
    }
    ///State transition - sets the `body` field to Set
    pub struct SetBody<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetBody<S> {}
    impl<S: State> State for SetBody<S> {
        type Body = Set<members::body>;
        type CreatedAt = S::CreatedAt;
        type Subject = S::Subject;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Body = S::Body;
        type CreatedAt = Set<members::created_at>;
        type Subject = S::Subject;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubject<S> {}
    impl<S: State> State for SetSubject<S> {
        type Body = S::Body;
        type CreatedAt = S::CreatedAt;
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `body` field
        pub struct body(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type
pub struct CommentBuilder<'a, S: comment_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<Datetime>,
        Option<StrongRef<'a>>,
        Option<StrongRef<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Comment<'a> {
    /// Create a new builder for this type
    pub fn new() -> CommentBuilder<'a, comment_state::Empty> {
        CommentBuilder::new()
    }
}

impl<'a> CommentBuilder<'a, comment_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        CommentBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommentBuilder<'a, S>
where
    S: comment_state::State,
    S::Body: comment_state::IsUnset,
{
    /// Set the `body` field (required)
    pub fn body(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> CommentBuilder<'a, comment_state::SetBody<S>> {
        self._fields.0 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommentBuilder<'a, S>
where
    S: comment_state::State,
    S::CreatedAt: comment_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> CommentBuilder<'a, comment_state::SetCreatedAt<S>> {
        self._fields.1 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: comment_state::State> CommentBuilder<'a, S> {
    /// Set the `replyTo` field (optional)
    pub fn reply_to(mut self, value: impl Into<Option<StrongRef<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `replyTo` field to an Option value (optional)
    pub fn maybe_reply_to(mut self, value: Option<StrongRef<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S> CommentBuilder<'a, S>
where
    S: comment_state::State,
    S::Subject: comment_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<StrongRef<'a>>,
    ) -> CommentBuilder<'a, comment_state::SetSubject<S>> {
        self._fields.3 = Option::Some(value.into());
        CommentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CommentBuilder<'a, S>
where
    S: comment_state::State,
    S::Body: comment_state::IsSet,
    S::CreatedAt: comment_state::IsSet,
    S::Subject: comment_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Comment<'a> {
        Comment {
            body: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            reply_to: self._fields.2,
            subject: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Comment<'a> {
        Comment {
            body: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            reply_to: self._fields.2,
            subject: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_ing_observ_temp_comment() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("ing.observ.temp.comment"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A comment on an observation. Used for general discussion, questions, or additional context about an observation.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("subject"), SmolStr::new_static("body"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("body"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("The text content of the comment."),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp when this comment was created.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("replyTo"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
