// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: ing.observ.temp.identification
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
use crate::ing_observ::temp::identification;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "ing.observ.temp.identification",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Identification<S: BosStr = DefaultStr> {
    ///Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<S>,
    ///Timestamp when this identification was created (Darwin Core dwc:dateIdentified).
    pub created_at: Datetime,
    ///If true, this identification agrees with the current community ID rather than proposing a new one.  Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default = "_default_identification_is_agreement")]
    pub is_agreement: Option<bool>,
    ///A strong reference (CID + URI) to the observation being identified.
    pub subject: StrongRef<S>,
    ///Index of the subject within the occurrence being identified. When multiple organisms are photographed together (e.g., butterfly on a flower), each gets a unique index starting from 0. Creating an identification with a new subjectIndex implicitly creates that subject.  Defaults to `0`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default = "_default_identification_subject_index")]
    pub subject_index: Option<i64>,
    ///The taxonomic determination being proposed (Darwin Core Taxon class).
    pub taxon: identification::Taxon<S>,
    ///[DEPRECATED: Use kingdom + scientificName for taxon resolution] External taxon identifier (e.g., gbif:2878688). Prefixed with source.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxon_id: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct IdentificationGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Identification<S>,
}

/// Taxonomic information following Darwin Core Taxon class (dwc:Taxon).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Taxon<S: BosStr = DefaultStr> {
    ///Taxonomic class (Darwin Core dwc:class).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub class: Option<S>,
    ///Taxonomic family (Darwin Core dwc:family).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub family: Option<S>,
    ///Taxonomic genus (Darwin Core dwc:genus).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub genus: Option<S>,
    ///Taxonomic kingdom (Darwin Core dwc:kingdom).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kingdom: Option<S>,
    ///Taxonomic order (Darwin Core dwc:order).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order: Option<S>,
    ///Taxonomic phylum (Darwin Core dwc:phylum).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phylum: Option<S>,
    ///The full scientific name (Darwin Core dwc:scientificName).
    pub scientific_name: S,
    ///The authorship information for the scientificName (Darwin Core dwc:scientificNameAuthorship).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scientific_name_authorship: Option<S>,
    ///The taxonomic rank of the identification (Darwin Core dwc:taxonRank).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxon_rank: Option<TaxonTaxonRank<S>>,
    ///Common name for the taxon in the identifier's language (Darwin Core dwc:vernacularName).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub vernacular_name: Option<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// The taxonomic rank of the identification (Darwin Core dwc:taxonRank).

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TaxonTaxonRank<S: BosStr = DefaultStr> {
    Kingdom,
    Phylum,
    Class,
    Order,
    Family,
    Genus,
    Species,
    Subspecies,
    Variety,
    Form,
    Other(S),
}

impl<S: BosStr> TaxonTaxonRank<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Kingdom => "kingdom",
            Self::Phylum => "phylum",
            Self::Class => "class",
            Self::Order => "order",
            Self::Family => "family",
            Self::Genus => "genus",
            Self::Species => "species",
            Self::Subspecies => "subspecies",
            Self::Variety => "variety",
            Self::Form => "form",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "kingdom" => Self::Kingdom,
            "phylum" => Self::Phylum,
            "class" => Self::Class,
            "order" => Self::Order,
            "family" => Self::Family,
            "genus" => Self::Genus,
            "species" => Self::Species,
            "subspecies" => Self::Subspecies,
            "variety" => Self::Variety,
            "form" => Self::Form,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for TaxonTaxonRank<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for TaxonTaxonRank<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for TaxonTaxonRank<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for TaxonTaxonRank<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for TaxonTaxonRank<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for TaxonTaxonRank<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = TaxonTaxonRank<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            TaxonTaxonRank::Kingdom => TaxonTaxonRank::Kingdom,
            TaxonTaxonRank::Phylum => TaxonTaxonRank::Phylum,
            TaxonTaxonRank::Class => TaxonTaxonRank::Class,
            TaxonTaxonRank::Order => TaxonTaxonRank::Order,
            TaxonTaxonRank::Family => TaxonTaxonRank::Family,
            TaxonTaxonRank::Genus => TaxonTaxonRank::Genus,
            TaxonTaxonRank::Species => TaxonTaxonRank::Species,
            TaxonTaxonRank::Subspecies => TaxonTaxonRank::Subspecies,
            TaxonTaxonRank::Variety => TaxonTaxonRank::Variety,
            TaxonTaxonRank::Form => TaxonTaxonRank::Form,
            TaxonTaxonRank::Other(v) => TaxonTaxonRank::Other(v.into_static()),
        }
    }
}

impl<S: BosStr> Identification<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, IdentificationRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentificationRecord;
impl XrpcResp for IdentificationRecord {
    const NSID: &'static str = "ing.observ.temp.identification";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = IdentificationGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<IdentificationGetRecordOutput<S>> for Identification<S> {
    fn from(output: IdentificationGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Identification<S> {
    const NSID: &'static str = "ing.observ.temp.identification";
    type Record = IdentificationRecord;
}

impl Collection for IdentificationRecord {
    const NSID: &'static str = "ing.observ.temp.identification";
    type Record = IdentificationRecord;
}

impl<S: BosStr> LexiconSchema for Identification<S> {
    fn nsid() -> &'static str {
        "ing.observ.temp.identification"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_ing_observ_temp_identification()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.comment {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("comment"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.subject_index {
            if *value > 99i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("subject_index"),
                    max: 99i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.subject_index {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("subject_index"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.taxon_id {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("taxon_id"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for Taxon<S> {
    fn nsid() -> &'static str {
        "ing.observ.temp.identification"
    }
    fn def_name() -> &'static str {
        "taxon"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_ing_observ_temp_identification()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.class {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("class"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.family {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("family"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.genus {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("genus"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.kingdom {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("kingdom"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.order {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("order"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.phylum {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("phylum"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.scientific_name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("scientific_name"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.scientific_name_authorship {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("scientific_name_authorship"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.taxon_rank {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("taxon_rank"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.vernacular_name {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("vernacular_name"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

fn _default_identification_is_agreement() -> Option<bool> {
    Some(false)
}

fn _default_identification_subject_index() -> Option<i64> {
    Some(0i64)
}

pub mod identification_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Subject;
        type Taxon;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Subject = Unset;
        type Taxon = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubject<St> {}
    impl<St: State> State for SetSubject<St> {
        type Subject = Set<members::subject>;
        type Taxon = St::Taxon;
        type CreatedAt = St::CreatedAt;
    }
    ///State transition - sets the `taxon` field to Set
    pub struct SetTaxon<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTaxon<St> {}
    impl<St: State> State for SetTaxon<St> {
        type Subject = St::Subject;
        type Taxon = Set<members::taxon>;
        type CreatedAt = St::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type Subject = St::Subject;
        type Taxon = St::Taxon;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `subject` field
        pub struct subject(());
        ///Marker type for the `taxon` field
        pub struct taxon(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type.
pub struct IdentificationBuilder<S: BosStr, St: identification_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<Datetime>,
        Option<bool>,
        Option<StrongRef<S>>,
        Option<i64>,
        Option<identification::Taxon<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> Identification<S> {
    /// Create a new builder for this type.
    pub fn new() -> IdentificationBuilder<S, identification_state::Empty> {
        IdentificationBuilder::new()
    }
}

impl<S: BosStr> IdentificationBuilder<S, identification_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        IdentificationBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `comment` field (optional)
    pub fn comment(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `comment` field to an Option value (optional)
    pub fn maybe_comment(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::CreatedAt: identification_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> IdentificationBuilder<S, identification_state::SetCreatedAt<St>> {
        self._fields.1 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `isAgreement` field (optional)
    pub fn is_agreement(mut self, value: impl Into<Option<bool>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `isAgreement` field to an Option value (optional)
    pub fn maybe_is_agreement(mut self, value: Option<bool>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::Subject: identification_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<StrongRef<S>>,
    ) -> IdentificationBuilder<S, identification_state::SetSubject<St>> {
        self._fields.3 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `subjectIndex` field (optional)
    pub fn subject_index(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `subjectIndex` field to an Option value (optional)
    pub fn maybe_subject_index(mut self, value: Option<i64>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::Taxon: identification_state::IsUnset,
{
    /// Set the `taxon` field (required)
    pub fn taxon(
        mut self,
        value: impl Into<identification::Taxon<S>>,
    ) -> IdentificationBuilder<S, identification_state::SetTaxon<St>> {
        self._fields.5 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `taxonId` field (optional)
    pub fn taxon_id(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `taxonId` field to an Option value (optional)
    pub fn maybe_taxon_id(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::Subject: identification_state::IsSet,
    St::Taxon: identification_state::IsSet,
    St::CreatedAt: identification_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Identification<S> {
        Identification {
            comment: self._fields.0,
            created_at: self._fields.1.unwrap(),
            is_agreement: self._fields.2.or_else(|| Some(false)),
            subject: self._fields.3.unwrap(),
            subject_index: self._fields.4.or_else(|| Some(0i64)),
            taxon: self._fields.5.unwrap(),
            taxon_id: self._fields.6,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Identification<S> {
        Identification {
            comment: self._fields.0,
            created_at: self._fields.1.unwrap(),
            is_agreement: self._fields.2.or_else(|| Some(false)),
            subject: self._fields.3.unwrap(),
            subject_index: self._fields.4.or_else(|| Some(0i64)),
            taxon: self._fields.5.unwrap(),
            taxon_id: self._fields.6,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_ing_observ_temp_identification() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("ing.observ.temp.identification"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("subject"),
                                SmolStr::new_static("taxon"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("comment"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).",
                                        ),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp when this identification was created (Darwin Core dwc:dateIdentified).",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("isAgreement"),
                                LexObjectProperty::Boolean(LexBoolean {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subjectIndex"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    maximum: Some(99i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("taxon"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("#taxon"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("taxonId"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "[DEPRECATED: Use kingdom + scientificName for taxon resolution] External taxon identifier (e.g., gbif:2878688). Prefixed with source.",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("taxon"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Taxonomic information following Darwin Core Taxon class (dwc:Taxon).",
                        ),
                    ),
                    required: Some(vec![SmolStr::new_static("scientificName")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("class"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic class (Darwin Core dwc:class).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("family"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic family (Darwin Core dwc:family).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("genus"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic genus (Darwin Core dwc:genus).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("kingdom"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic kingdom (Darwin Core dwc:kingdom).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("order"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic order (Darwin Core dwc:order).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("phylum"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Taxonomic phylum (Darwin Core dwc:phylum).",
                                    ),
                                ),
                                max_length: Some(64usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scientificName"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The full scientific name (Darwin Core dwc:scientificName).",
                                    ),
                                ),
                                max_length: Some(256usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("scientificNameAuthorship"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The authorship information for the scientificName (Darwin Core dwc:scientificNameAuthorship).",
                                    ),
                                ),
                                max_length: Some(256usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("taxonRank"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "The taxonomic rank of the identification (Darwin Core dwc:taxonRank).",
                                    ),
                                ),
                                max_length: Some(32usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("vernacularName"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "Common name for the taxon in the identifier's language (Darwin Core dwc:vernacularName).",
                                    ),
                                ),
                                max_length: Some(256usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
