// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: ing.observ.temp.interaction
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
use crate::ing_observ::temp::identification::Taxon;
use crate::ing_observ::temp::interaction;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A subject in an interaction - can reference an existing occurrence or just specify a taxon.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct InteractionSubject<S: BosStr = DefaultStr> {
    ///Reference to an existing occurrence record.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub occurrence: Option<StrongRef<S>>,
    ///Index of the subject within the occurrence (for multi-subject observations).  Defaults to `0`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default = "_default_interaction_subject_subject_index")]
    pub subject_index: Option<i64>,
    ///Taxonomic information for the organism (for unobserved subjects or to specify the taxon).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxon: Option<Taxon<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Species interaction documenting ecological relationship between organisms.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "ing.observ.temp.interaction",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Interaction<S: BosStr = DefaultStr> {
    ///Additional notes about the interaction.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<S>,
    ///Timestamp when this record was created.
    pub created_at: Datetime,
    ///Direction of the interaction: AtoB means A acts on B, BtoA means B acts on A, bidirectional means mutual.  Defaults to `"AtoB"`.
    #[serde(default = "_default_interaction_direction")]
    pub direction: S,
    ///Type of ecological interaction between the subjects.
    pub interaction_type: InteractionInteractionType<S>,
    ///The first subject (actor) in the interaction.
    pub subject_a: interaction::InteractionSubject<S>,
    ///The second subject (recipient) in the interaction.
    pub subject_b: interaction::InteractionSubject<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Type of ecological interaction between the subjects.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum InteractionInteractionType<S: BosStr = DefaultStr> {
    Predation,
    Pollination,
    Parasitism,
    Herbivory,
    Symbiosis,
    Mutualism,
    Competition,
    Shelter,
    Transportation,
    Oviposition,
    SeedDispersal,
    Other(S),
}

impl<S: BosStr> InteractionInteractionType<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Predation => "predation",
            Self::Pollination => "pollination",
            Self::Parasitism => "parasitism",
            Self::Herbivory => "herbivory",
            Self::Symbiosis => "symbiosis",
            Self::Mutualism => "mutualism",
            Self::Competition => "competition",
            Self::Shelter => "shelter",
            Self::Transportation => "transportation",
            Self::Oviposition => "oviposition",
            Self::SeedDispersal => "seed_dispersal",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "predation" => Self::Predation,
            "pollination" => Self::Pollination,
            "parasitism" => Self::Parasitism,
            "herbivory" => Self::Herbivory,
            "symbiosis" => Self::Symbiosis,
            "mutualism" => Self::Mutualism,
            "competition" => Self::Competition,
            "shelter" => Self::Shelter,
            "transportation" => Self::Transportation,
            "oviposition" => Self::Oviposition,
            "seed_dispersal" => Self::SeedDispersal,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for InteractionInteractionType<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for InteractionInteractionType<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for InteractionInteractionType<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for InteractionInteractionType<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for InteractionInteractionType<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for InteractionInteractionType<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = InteractionInteractionType<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            InteractionInteractionType::Predation => InteractionInteractionType::Predation,
            InteractionInteractionType::Pollination => InteractionInteractionType::Pollination,
            InteractionInteractionType::Parasitism => InteractionInteractionType::Parasitism,
            InteractionInteractionType::Herbivory => InteractionInteractionType::Herbivory,
            InteractionInteractionType::Symbiosis => InteractionInteractionType::Symbiosis,
            InteractionInteractionType::Mutualism => InteractionInteractionType::Mutualism,
            InteractionInteractionType::Competition => InteractionInteractionType::Competition,
            InteractionInteractionType::Shelter => InteractionInteractionType::Shelter,
            InteractionInteractionType::Transportation => {
                InteractionInteractionType::Transportation
            }
            InteractionInteractionType::Oviposition => InteractionInteractionType::Oviposition,
            InteractionInteractionType::SeedDispersal => InteractionInteractionType::SeedDispersal,
            InteractionInteractionType::Other(v) => {
                InteractionInteractionType::Other(v.into_static())
            }
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct InteractionGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Interaction<S>,
}

impl<S: BosStr> Interaction<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, InteractionRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

impl<S: BosStr> LexiconSchema for InteractionSubject<S> {
    fn nsid() -> &'static str {
        "ing.observ.temp.interaction"
    }
    fn def_name() -> &'static str {
        "interactionSubject"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_ing_observ_temp_interaction()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.subject_index {
            if *value > 99i64 {
                return Err(ConstraintError::Maximum {
                    path: ValidationPath::from_field("subject_index"),
                    max: 99i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.subject_index {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("subject_index"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct InteractionRecord;
impl XrpcResp for InteractionRecord {
    const NSID: &'static str = "ing.observ.temp.interaction";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = InteractionGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<InteractionGetRecordOutput<S>> for Interaction<S> {
    fn from(output: InteractionGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Interaction<S> {
    const NSID: &'static str = "ing.observ.temp.interaction";
    type Record = InteractionRecord;
}

impl Collection for InteractionRecord {
    const NSID: &'static str = "ing.observ.temp.interaction";
    type Record = InteractionRecord;
}

impl<S: BosStr> LexiconSchema for Interaction<S> {
    fn nsid() -> &'static str {
        "ing.observ.temp.interaction"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_ing_observ_temp_interaction()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.comment {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("comment"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.interaction_type;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("interaction_type"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

fn _default_interaction_subject_subject_index() -> Option<i64> {
    Some(0i64)
}

impl Default for InteractionSubject {
    fn default() -> Self {
        Self {
            occurrence: None,
            subject_index: Some(0i64),
            taxon: None,
            extra_data: Default::default(),
        }
    }
}

fn lexicon_doc_ing_observ_temp_interaction() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("ing.observ.temp.interaction"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("interactionSubject"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "A subject in an interaction - can reference an existing occurrence or just specify a taxon.",
                        ),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("occurrence"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("subjectIndex"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                maximum: Some(99i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("taxon"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static(
                                    "ing.observ.temp.identification#taxon",
                                ),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Species interaction documenting ecological relationship between organisms.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("subjectA"),
                                SmolStr::new_static("subjectB"),
                                SmolStr::new_static("interactionType"),
                                SmolStr::new_static("direction"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("comment"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Additional notes about the interaction.",
                                        ),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp when this record was created.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("direction"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Direction of the interaction: AtoB means A acts on B, BtoA means B acts on A, bidirectional means mutual.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("interactionType"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Type of ecological interaction between the subjects.",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subjectA"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("#interactionSubject"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subjectB"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("#interactionSubject"),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

fn _default_interaction_direction<S: FromStaticStr>() -> S {
    S::from_static("AtoB")
}

pub mod interaction_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type SubjectA;
        type Direction;
        type SubjectB;
        type CreatedAt;
        type InteractionType;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type SubjectA = Unset;
        type Direction = Unset;
        type SubjectB = Unset;
        type CreatedAt = Unset;
        type InteractionType = Unset;
    }
    ///State transition - sets the `subject_a` field to Set
    pub struct SetSubjectA<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubjectA<St> {}
    impl<St: State> State for SetSubjectA<St> {
        type SubjectA = Set<members::subject_a>;
        type Direction = St::Direction;
        type SubjectB = St::SubjectB;
        type CreatedAt = St::CreatedAt;
        type InteractionType = St::InteractionType;
    }
    ///State transition - sets the `direction` field to Set
    pub struct SetDirection<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDirection<St> {}
    impl<St: State> State for SetDirection<St> {
        type SubjectA = St::SubjectA;
        type Direction = Set<members::direction>;
        type SubjectB = St::SubjectB;
        type CreatedAt = St::CreatedAt;
        type InteractionType = St::InteractionType;
    }
    ///State transition - sets the `subject_b` field to Set
    pub struct SetSubjectB<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubjectB<St> {}
    impl<St: State> State for SetSubjectB<St> {
        type SubjectA = St::SubjectA;
        type Direction = St::Direction;
        type SubjectB = Set<members::subject_b>;
        type CreatedAt = St::CreatedAt;
        type InteractionType = St::InteractionType;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type SubjectA = St::SubjectA;
        type Direction = St::Direction;
        type SubjectB = St::SubjectB;
        type CreatedAt = Set<members::created_at>;
        type InteractionType = St::InteractionType;
    }
    ///State transition - sets the `interaction_type` field to Set
    pub struct SetInteractionType<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetInteractionType<St> {}
    impl<St: State> State for SetInteractionType<St> {
        type SubjectA = St::SubjectA;
        type Direction = St::Direction;
        type SubjectB = St::SubjectB;
        type CreatedAt = St::CreatedAt;
        type InteractionType = Set<members::interaction_type>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `subject_a` field
        pub struct subject_a(());
        ///Marker type for the `direction` field
        pub struct direction(());
        ///Marker type for the `subject_b` field
        pub struct subject_b(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `interaction_type` field
        pub struct interaction_type(());
    }
}

/// Builder for constructing an instance of this type.
pub struct InteractionBuilder<S: BosStr, St: interaction_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<Datetime>,
        Option<S>,
        Option<InteractionInteractionType<S>>,
        Option<interaction::InteractionSubject<S>>,
        Option<interaction::InteractionSubject<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> Interaction<S> {
    /// Create a new builder for this type.
    pub fn new() -> InteractionBuilder<S, interaction_state::Empty> {
        InteractionBuilder::new()
    }
}

impl<S: BosStr> InteractionBuilder<S, interaction_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        InteractionBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: interaction_state::State> InteractionBuilder<S, St> {
    /// Set the `comment` field (optional)
    pub fn comment(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `comment` field to an Option value (optional)
    pub fn maybe_comment(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::CreatedAt: interaction_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> InteractionBuilder<S, interaction_state::SetCreatedAt<St>> {
        self._fields.1 = Option::Some(value.into());
        InteractionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::Direction: interaction_state::IsUnset,
{
    /// Set the `direction` field (required)
    pub fn direction(
        mut self,
        value: impl Into<S>,
    ) -> InteractionBuilder<S, interaction_state::SetDirection<St>> {
        self._fields.2 = Option::Some(value.into());
        InteractionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::InteractionType: interaction_state::IsUnset,
{
    /// Set the `interactionType` field (required)
    pub fn interaction_type(
        mut self,
        value: impl Into<InteractionInteractionType<S>>,
    ) -> InteractionBuilder<S, interaction_state::SetInteractionType<St>> {
        self._fields.3 = Option::Some(value.into());
        InteractionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::SubjectA: interaction_state::IsUnset,
{
    /// Set the `subjectA` field (required)
    pub fn subject_a(
        mut self,
        value: impl Into<interaction::InteractionSubject<S>>,
    ) -> InteractionBuilder<S, interaction_state::SetSubjectA<St>> {
        self._fields.4 = Option::Some(value.into());
        InteractionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::SubjectB: interaction_state::IsUnset,
{
    /// Set the `subjectB` field (required)
    pub fn subject_b(
        mut self,
        value: impl Into<interaction::InteractionSubject<S>>,
    ) -> InteractionBuilder<S, interaction_state::SetSubjectB<St>> {
        self._fields.5 = Option::Some(value.into());
        InteractionBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> InteractionBuilder<S, St>
where
    St: interaction_state::State,
    St::SubjectA: interaction_state::IsSet,
    St::Direction: interaction_state::IsSet,
    St::SubjectB: interaction_state::IsSet,
    St::CreatedAt: interaction_state::IsSet,
    St::InteractionType: interaction_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Interaction<S> {
        Interaction {
            comment: self._fields.0,
            created_at: self._fields.1.unwrap(),
            direction: self._fields.2.unwrap(),
            interaction_type: self._fields.3.unwrap(),
            subject_a: self._fields.4.unwrap(),
            subject_b: self._fields.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Interaction<S> {
        Interaction {
            comment: self._fields.0,
            created_at: self._fields.1.unwrap(),
            direction: self._fields.2.unwrap(),
            interaction_type: self._fields.3.unwrap(),
            subject_a: self._fields.4.unwrap(),
            subject_b: self._fields.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
