steps:
  # Build all images in parallel
  - id: 'build-appview'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'crates/observing-appview/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/observing-appview', '.']
    waitFor: ['-']

  - id: 'build-ingester'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'crates/observing-ingester/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/observing-ingester', '.']
    waitFor: ['-']

  - id: 'build-media-proxy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'crates/observing-media-proxy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/observing-media-proxy', '.']
    waitFor: ['-']

  - id: 'build-taxonomy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'crates/observing-taxonomy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/observing-taxonomy', '.']
    waitFor: ['-']

  # Push all images in parallel
  - id: 'push-appview'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/observing-appview']
    waitFor: ['build-appview']

  - id: 'push-ingester'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/observing-ingester']
    waitFor: ['build-ingester']

  - id: 'push-media-proxy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/observing-media-proxy']
    waitFor: ['build-media-proxy']

  - id: 'push-taxonomy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/observing-taxonomy']
    waitFor: ['build-taxonomy']

  # Deploy all services in parallel
  - id: 'deploy-appview'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'observing-appview'
      - '--image=gcr.io/$PROJECT_ID/observing-appview'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:observing-db'
      - '--set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:observing-db,DB_NAME=observing,DB_USER=postgres,PUBLIC_URL=$_PUBLIC_URL,TAXONOMY_SERVICE_URL=$_TAXONOMY_URL'
      - '--set-secrets=DB_PASSWORD=observing-db-password:latest,INTERNAL_SECRET=observing-internal-secret:latest'
    waitFor: ['push-appview']

  - id: 'deploy-ingester'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'observing-ingester'
      - '--image=gcr.io/$PROJECT_ID/observing-ingester'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:observing-db'
      - '--set-env-vars=RUST_LOG=observing_ingester=info,DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:observing-db,DB_NAME=observing,DB_USER=postgres,JETSTREAM_URL=wss://jetstream2.us-east.bsky.network/subscribe'
      - '--set-secrets=DB_PASSWORD=observing-db-password:latest'
      - '--min-instances=1'
      - '--max-instances=1'
      - '--timeout=3600'
    waitFor: ['push-ingester']

  - id: 'deploy-media-proxy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'observing-media-proxy'
      - '--image=gcr.io/$PROJECT_ID/observing-media-proxy'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars=RUST_LOG=observing_media_proxy=info'
    waitFor: ['push-media-proxy']

  - id: 'deploy-taxonomy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'observing-taxonomy'
      - '--image=gcr.io/$PROJECT_ID/observing-taxonomy'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars=RUST_LOG=observing_taxonomy=info'
    waitFor: ['push-taxonomy']

images:
  - 'gcr.io/$PROJECT_ID/observing-appview'
  - 'gcr.io/$PROJECT_ID/observing-ingester'
  - 'gcr.io/$PROJECT_ID/observing-media-proxy'
  - 'gcr.io/$PROJECT_ID/observing-taxonomy'

substitutions:
  _REGION: us-central1
  _PUBLIC_URL: https://observing-appview-378013734384.us-central1.run.app
  _TAXONOMY_URL: https://observing-taxonomy-378013734384.us-central1.run.app
