steps:
  # Build all images in parallel
  - id: 'build-appview'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'packages/biosky-appview/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/biosky-appview', '.']
    waitFor: ['-']

  - id: 'build-api'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'packages/biosky-api/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/biosky-api', '.']
    waitFor: ['-']

  - id: 'build-ingester'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/biosky-ingester', 'packages/biosky-ingester']
    waitFor: ['-']

  - id: 'build-media-proxy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'packages/biosky-media-proxy/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/biosky-media-proxy', '.']
    waitFor: ['-']

  # Push all images in parallel
  - id: 'push-appview'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/biosky-appview']
    waitFor: ['build-appview']

  - id: 'push-api'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/biosky-api']
    waitFor: ['build-api']

  - id: 'push-ingester'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/biosky-ingester']
    waitFor: ['build-ingester']

  - id: 'push-media-proxy'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/biosky-media-proxy']
    waitFor: ['build-media-proxy']

  # Deploy all services in parallel
  - id: 'deploy-appview'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biosky-appview'
      - '--image=gcr.io/$PROJECT_ID/biosky-appview'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:biosky-db'
      - '--set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:biosky-db,DB_NAME=biosky,DB_USER=postgres,PUBLIC_URL=$_PUBLIC_URL'
      - '--set-secrets=DB_PASSWORD=biosky-db-password:latest,INTERNAL_SECRET=biosky-internal-secret:latest'
    waitFor: ['push-appview']

  - id: 'deploy-api'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biosky-api'
      - '--image=gcr.io/$PROJECT_ID/biosky-api'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:biosky-db'
      - '--set-env-vars=DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:biosky-db,DB_NAME=biosky,DB_USER=postgres,APPVIEW_URL=$_APPVIEW_URL,CORS_ORIGINS=$_PUBLIC_URL'
      - '--set-secrets=DB_PASSWORD=biosky-db-password:latest,INTERNAL_SECRET=biosky-internal-secret:latest'
    waitFor: ['push-api']

  - id: 'deploy-ingester'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biosky-ingester'
      - '--image=gcr.io/$PROJECT_ID/biosky-ingester'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--cpu=1'
      - '--memory=2Gi'
      - '--add-cloudsql-instances=$PROJECT_ID:$_REGION:biosky-db'
      - '--set-env-vars=RUST_LOG=biosky_ingester=info,DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:biosky-db,DB_NAME=biosky,DB_USER=postgres,JETSTREAM_URL=wss://jetstream2.us-east.bsky.network/subscribe'
      - '--set-secrets=DB_PASSWORD=biosky-db-password:latest'
      - '--min-instances=1'
      - '--max-instances=1'
      - '--timeout=3600'
    waitFor: ['push-ingester']

  - id: 'deploy-media-proxy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'biosky-media-proxy'
      - '--image=gcr.io/$PROJECT_ID/biosky-media-proxy'
      - '--region=$_REGION'
      - '--allow-unauthenticated'
      - '--set-env-vars=RUST_LOG=biosky_media_proxy=info,LOG_FORMAT=json'
    waitFor: ['push-media-proxy']

images:
  - 'gcr.io/$PROJECT_ID/biosky-appview'
  - 'gcr.io/$PROJECT_ID/biosky-api'
  - 'gcr.io/$PROJECT_ID/biosky-ingester'
  - 'gcr.io/$PROJECT_ID/biosky-media-proxy'

substitutions:
  _REGION: us-central1
  _PUBLIC_URL: https://biosky-appview-378013734384.us-central1.run.app
  _APPVIEW_URL: https://biosky-appview-378013734384.us-central1.run.app
