version: "0.5"

processes:
  cloud-sql-proxy:
    command: cloud-sql-proxy --port 5432 frewsxcv:us-central1:observing-db
    readiness_probe:
      exec:
        command: pg_isready -h localhost -p 5432

  appview:
    command: npm run appview
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:${DB_PASSWORD}@localhost:5432/observing}
    readiness_probe:
      http_get:
        host: localhost
        port: 3000
        path: /health
    depends_on:
      cloud-sql-proxy:
        condition: process_healthy

  api:
    command: npm run api
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:${DB_PASSWORD}@localhost:5432/observing}
      - PORT=3002
    readiness_probe:
      http_get:
        host: localhost
        port: 3002
        path: /health
    depends_on:
      cloud-sql-proxy:
        condition: process_healthy

  frontend:
    command: npm run frontend:dev
    depends_on:
      appview:
        condition: process_healthy

  media-proxy:
    command: cargo run -p observing-media-proxy
    environment:
      - PORT=3001
      - CACHE_DIR=./cache/media
    readiness_probe:
      http_get:
        host: localhost
        port: 3001
        path: /health

  ingester:
    command: cargo run
    working_dir: packages/observing-ingester
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:${DB_PASSWORD}@localhost:5432/observing}
    depends_on:
      cloud-sql-proxy:
        condition: process_healthy

  taxonomy:
    command: cargo run -p observing-taxonomy
    environment:
      - PORT=3003
    readiness_probe:
      http_get:
        host: localhost
        port: 3003
        path: /health
