// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";

export type CreateOccurrenceRequest = { scientificName?: string, latitude: number, longitude: number, coordinateUncertaintyInMeters?: number, notes?: string, eventDate?: string, images?: Array<ImageUpload>, taxonId?: string, taxonRank?: string, vernacularName?: string, kingdom?: string, phylum?: string, class?: string, order?: string, family?: string, genus?: string, recordedBy?: Array<string>, };
