// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateCommentRequest = { occurrenceUri: string, occurrenceCid: string, body: string, replyToUri?: string, replyToCid?: string, };
