// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateIdentificationRequest = {
  occurrenceUri: string;
  occurrenceCid: string;
  scientificName: string;
  taxonRank?: string;
  /**
   * Optional kingdom hint from a GBIF autocomplete pick. Disambiguates
   * genus-level names for the GBIF validate call and acts as a fallback
   * when validation doesn't return a kingdom of its own.
   */
  kingdom?: string;
};
