// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";

export type CreateOccurrenceRequest = {
  latitude: number;
  longitude: number;
  coordinateUncertaintyInMeters?: number;
  eventDate?: string;
  images?: Array<ImageUpload>;
  scientificName?: string;
  taxonRank?: string;
  /**
   * Optional kingdom hint from a GBIF autocomplete pick. Disambiguates
   * genus-level names for the auto-identification's GBIF validate call
   * and acts as a fallback when validation doesn't return a kingdom.
   */
  kingdom?: string;
};
