// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";

export type CreateIdentificationRequest = { occurrenceUri: string, occurrenceCid: string, subjectIndex?: number, taxonName: string, taxonRank?: string, comment?: string, isAgreement?: boolean, confidence?: Confidence, };
