// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";

export type CreateOccurrenceRequest = { latitude: number, longitude: number, coordinateUncertaintyInMeters?: number, notes?: string, eventDate?: string, images?: Array<ImageUpload>, recordedBy?: Array<string>, };
