// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateIdentificationRequest = {
  occurrenceUri: string;
  occurrenceCid: string;
  subjectIndex?: number;
  scientificName: string;
  taxonRank?: string;
  comment?: string;
  isAgreement?: boolean;
};
