// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrosspostStatusResponse = {
  /**
   * Null when the occurrence has never been queued for cross-posting.
   */
  status: "pending" | "synced" | "failed" | null;
  /**
   * Why the last attempt failed, if it did.
   */
  lastError: string | null;
  /**
   * The iNaturalist observation, once it exists. This is the
   * `externalRecords` entry that cross-posting owns.
   */
  inatUrl: string | null;
};
