// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { InteractionDirection } from "./InteractionDirection";
import type { Profile } from "./Profile";

/**
 * Enriched interaction with profile info
 */
export type EnrichedInteraction = {
  creator: Profile;
  uri: string;
  cid: string;
  did: string;
  subject_a_occurrence_uri?: string;
  subject_a_occurrence_cid?: string;
  subject_a_subject_index?: number;
  subject_a_taxon_name?: string;
  subject_a_kingdom?: string;
  subject_b_occurrence_uri?: string;
  subject_b_occurrence_cid?: string;
  subject_b_subject_index?: number;
  subject_b_taxon_name?: string;
  subject_b_kingdom?: string;
  interaction_type: string;
  direction: InteractionDirection;
  confidence?: Confidence;
  comment?: string;
  created_at: string;
  indexed_at?: string;
};
