// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to this occurrence as held by another service — an iNaturalist
 * observation, a record in another AT Protocol lexicon, and so on. Passed
 * through verbatim: the appview neither resolves nor validates the target.
 */
export type ExternalRecord = {
  uri: string;
  /**
   * Short service identifier from the record (`inaturalist`, `bugguide`, an
   * AT Protocol app name, ...). The lexicon's known values are not
   * exhaustive, so clients must handle unfamiliar ones.
   */
  service?: string;
};
