// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageUpload = {
  /**
   * Base64-encoded image bytes.
   */
  data: string;
  /**
   * Deserialized from frontend but unused — PDS infers MIME type from bytes.
   */
  mimeType: string;
};
