// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObserverRole } from "./ObserverRole";

export type Observer = {
  did: string;
  role: ObserverRole;
  handle?: string;
  displayName?: string;
  avatar?: string;
};
