// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveTaxonomy } from "./EffectiveTaxonomy";
import type { Location } from "./Location";
import type { OccurrenceImage } from "./OccurrenceImage";
import type { Profile } from "./Profile";

/**
 * Enriched occurrence ready for API response
 */
export type Occurrence = {
  uri: string;
  cid: string;
  observer: Profile;
  communityId?: string;
  effectiveTaxonomy?: EffectiveTaxonomy;
  identificationCount: number;
  /**
   * NULL on survey-based occurrences whose `eventDate` lives on the
   * referenced survey record we don't yet ingest. The explore page
   * renders a placeholder rather than dropping the observation.
   */
  eventDate?: string;
  location?: Location;
  images: Array<OccurrenceImage>;
  createdAt: string;
  likeCount?: number;
  viewerHasLiked?: boolean;
  /**
   * Stable string codes from [`observing_db::quality`]. Empty means the
   * observation is "verifiable" — pass `?quality=verifiable` on feed
   * requests to filter to just those rows.
   */
  qualityIssues: Array<string>;
};
