// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectiveTaxonomy } from "./EffectiveTaxonomy";
import type { Location } from "./Location";
import type { Observer } from "./Observer";
import type { Profile } from "./Profile";
import type { Subject } from "./Subject";

/**
 * Enriched occurrence ready for API response
 */
export type Occurrence = {
  uri: string;
  cid: string;
  observer: Profile;
  observers: Array<Observer>;
  communityId?: string;
  effectiveTaxonomy?: EffectiveTaxonomy;
  subjects: Array<Subject>;
  eventDate: string;
  location: Location;
  verbatimLocality?: string;
  occurrenceRemarks?: string;
  images: Array<string>;
  createdAt: string;
  likeCount?: number;
  viewerHasLiked?: boolean;
};
