// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single image attached to an occurrence, with the SPDX license the
 * uploader chose (when one is recorded on the underlying media record).
 */
export type OccurrenceImage = { url: string; license?: string };
