// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Profile = { did: string, handle?: string, displayName?: string, avatar?: string, };
