// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityIssue =
  | "MISSING_DATE"
  | "MISSING_LOCATION"
  | "MISSING_MEDIA"
  | "COORDINATES_IMPRECISE"
  | "NO_CONSENSUS_ID";
