// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single data-quality criterion a feed row can be required to meet. Each is
 * the positive counterpart of a [`QualityIssue`] — a row meets the criterion
 * when the corresponding issue is *absent* (see [`compute_issues`]).
 *
 * [`PreciseLocation`](QualityCriterion::PreciseLocation) additionally implies
 * the location is present, mirroring the observation data-quality checklist:
 * precision can't be "met" when there are no coordinates at all (the issue is
 * suppressed in that case rather than reported).
 *
 * The serde representation is the single source of truth for the wire tokens:
 * it is exported to the frontend as `bindings/QualityCriterion.ts` and reused
 * by [`FromStr`] below, so the UI, the `?quality=` parser, and the generated
 * type can't drift.
 */
export type QualityCriterion =
  | "HAS_DATE"
  | "HAS_LOCATION"
  | "PRECISE_LOCATION"
  | "HAS_MEDIA"
  | "HAS_CONSENSUS_ID";
