// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single ranked species suggestion returned by the identification service.
 *
 * `kingdom` is used by the frontend for the taxon link target and is passed
 * to GBIF's `match_name` as a disambiguator when the appview enriches a
 * missing common name.
 */
export type SpeciesSuggestion = {
  scientificName: string;
  confidence: number;
  commonName?: string;
  kingdom?: string;
  /**
   * Whether this species' iNat range covers the request lat/lon.
   * `None` when geo lookup wasn't performed (no lat/lon, no geo index)
   * or when the cell at the request point is unknown to the index — i.e.
   * the field is only populated with an opinion when one is well-founded.
   */
  inRange?: boolean;
};
