// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpeciesSuggestion = { scientificName: string, confidence: number, commonName?: string, kingdom?: string, phylum?: string, class?: string, order?: string, family?: string, genus?: string, };
