// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simple success/failure response with no additional payload.
 */
export type SuccessResponse = { success: boolean };
