// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConservationStatus } from "./ConservationStatus";
import type { TaxaResult } from "./TaxaResult";
import type { TaxonAncestor } from "./TaxonAncestor";
import type { TaxonDescription } from "./TaxonDescription";
import type { TaxonMedia } from "./TaxonMedia";
import type { TaxonReference } from "./TaxonReference";

export type TaxonDetailWithCount = {
  observationCount: bigint;
  id: string;
  scientificName: string;
  commonName?: string;
  photoUrl?: string;
  rank: string;
  kingdom?: string;
  phylum?: string;
  class?: string;
  order?: string;
  family?: string;
  genus?: string;
  species?: string;
  source: string;
  conservationStatus?: ConservationStatus;
  description?: string;
  wikidataId?: string;
  ancestors: Array<TaxonAncestor>;
  children: Array<TaxaResult>;
  numDescendants?: number;
  extinct?: boolean;
  descriptions?: Array<TaxonDescription>;
  references?: Array<TaxonReference>;
  media?: Array<TaxonMedia>;
  gbifUrl?: string;
  wikidataUrl?: string;
};
