// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePreferencesRequest = {
  /**
   * Pass `null` to clear the user's saved default.
   */
  defaultLicense: string | null;
  /**
   * Map basemap id ("outdoor" | "topo" | "streets" | "satellite"). Pass
   * `null` to clear.
   */
  basemap: string | null;
};
