// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageUpload } from "./ImageUpload";

export type UpdateOccurrenceRequest = {
  uri: string;
  latitude: number;
  longitude: number;
  coordinateUncertaintyInMeters?: number;
  eventDate?: string;
  /**
   * Newly-added images to upload and attach, in addition to any retained ones.
   */
  images?: Array<ImageUpload>;
  /**
   * Blob CIDs of existing media records to retain on the updated occurrence.
   * Media whose CID is not in this list is dropped from the record.
   */
  retainedBlobCids?: Array<string>;
  scientificName?: string;
  taxonRank?: string;
  /**
   * See `CreateOccurrenceRequest::kingdom`.
   */
  kingdom?: string;
};
