// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaxaResult } from "./TaxaResult";

export type ValidateResponse = { valid: boolean, matchedName?: string, taxon?: TaxaResult, suggestions?: Array<TaxaResult>, };
