// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: org.rwell.test.interaction
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// A subject in an interaction - can reference an existing occurrence or just specify a taxon name.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct InteractionSubject<'a> {
    /// Taxonomic kingdom to disambiguate homonyms.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub kingdom: std::option::Option<jacquard_common::CowStr<'a>>,
    /// Reference to an existing occurrence record.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub occurrence: std::option::Option<
        crate::com_atproto::repo::strong_ref::StrongRef<'a>,
    >,
    /// Index of the subject within the occurrence (for multi-subject observations).
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub subject_index: std::option::Option<i64>,
    /// Scientific name of the organism (for unobserved subjects or to override occurrence ID).
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub taxon_name: std::option::Option<jacquard_common::CowStr<'a>>,
}

fn lexicon_doc_org_rwell_test_interaction() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("org.rwell.test.interaction"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("interactionSubject"),
                ::jacquard_lexicon::lexicon::LexUserType::Object(::jacquard_lexicon::lexicon::LexObject {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "A subject in an interaction - can reference an existing occurrence or just specify a taxon name.",
                        ),
                    ),
                    required: None,
                    nullable: None,
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = ::std::collections::BTreeMap::new();
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static("kingdom"),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Taxonomic kingdom to disambiguate homonyms.",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: Some(64usize),
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "occurrence",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                description: None,
                                r#ref: ::jacquard_common::CowStr::new_static(
                                    "com.atproto.repo.strongRef",
                                ),
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "subjectIndex",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                description: None,
                                default: None,
                                minimum: Some(0i64),
                                maximum: Some(99i64),
                                r#enum: None,
                                r#const: None,
                            }),
                        );
                        map.insert(
                            ::jacquard_common::smol_str::SmolStr::new_static(
                                "taxonName",
                            ),
                            ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                description: Some(
                                    ::jacquard_common::CowStr::new_static(
                                        "Scientific name of the organism (for unobserved subjects or to override occurrence ID).",
                                    ),
                                ),
                                format: None,
                                default: None,
                                min_length: None,
                                max_length: Some(256usize),
                                min_graphemes: None,
                                max_graphemes: None,
                                r#enum: None,
                                r#const: None,
                                known_values: None,
                            }),
                        );
                        map
                    },
                }),
            );
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Species interaction documenting ecological relationship between organisms.",
                        ),
                    ),
                    key: Some(::jacquard_common::CowStr::new_static("tid")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: Some(
                            vec![
                                ::jacquard_common::smol_str::SmolStr::new_static("subjectA"),
                                ::jacquard_common::smol_str::SmolStr::new_static("subjectB"),
                                ::jacquard_common::smol_str::SmolStr::new_static("interactionType"),
                                ::jacquard_common::smol_str::SmolStr::new_static("direction"),
                                ::jacquard_common::smol_str::SmolStr::new_static("createdAt")
                            ],
                        ),
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("comment"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Additional notes about the interaction.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: Some(3000usize),
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "confidence",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Confidence level in the interaction observation.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "createdAt",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Timestamp when this record was created.",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "direction",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Direction of the interaction: AtoB means A acts on B, BtoA means B acts on A, bidirectional means mutual.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "interactionType",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Type of ecological interaction between the subjects.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: Some(64usize),
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "subjectA",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                    description: None,
                                    r#ref: ::jacquard_common::CowStr::new_static(
                                        "#interactionSubject",
                                    ),
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "subjectB",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                    description: None,
                                    r#ref: ::jacquard_common::CowStr::new_static(
                                        "#interactionSubject",
                                    ),
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for InteractionSubject<'a> {
    fn nsid() -> &'static str {
        "org.rwell.test.interaction"
    }
    fn def_name() -> &'static str {
        "interactionSubject"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_org_rwell_test_interaction()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        if let Some(ref value) = self.kingdom {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(::jacquard_lexicon::validation::ConstraintError::MaxLength {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "kingdom",
                    ),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.subject_index {
            if *value > 99i64 {
                return Err(::jacquard_lexicon::validation::ConstraintError::Maximum {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "subject_index",
                    ),
                    max: 99i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.subject_index {
            if *value < 0i64 {
                return Err(::jacquard_lexicon::validation::ConstraintError::Minimum {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "subject_index",
                    ),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.taxon_name {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(::jacquard_lexicon::validation::ConstraintError::MaxLength {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "taxon_name",
                    ),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

/// Species interaction documenting ecological relationship between organisms.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Interaction<'a> {
    /// Additional notes about the interaction.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub comment: std::option::Option<jacquard_common::CowStr<'a>>,
    /// Confidence level in the interaction observation.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub confidence: std::option::Option<jacquard_common::CowStr<'a>>,
    /// Timestamp when this record was created.
    pub created_at: jacquard_common::types::string::Datetime,
    /// Direction of the interaction: AtoB means A acts on B, BtoA means B acts on A, bidirectional means mutual.
    #[serde(borrow)]
    pub direction: jacquard_common::CowStr<'a>,
    /// Type of ecological interaction between the subjects.
    #[serde(borrow)]
    pub interaction_type: jacquard_common::CowStr<'a>,
    /// The first subject (actor) in the interaction.
    #[serde(borrow)]
    pub subject_a: crate::org_rwell::test::interaction::InteractionSubject<'a>,
    /// The second subject (recipient) in the interaction.
    #[serde(borrow)]
    pub subject_b: crate::org_rwell::test::interaction::InteractionSubject<'a>,
}

pub mod interaction_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type SubjectB;
        type Direction;
        type CreatedAt;
        type SubjectA;
        type InteractionType;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type SubjectB = Unset;
        type Direction = Unset;
        type CreatedAt = Unset;
        type SubjectA = Unset;
        type InteractionType = Unset;
    }
    ///State transition - sets the `subject_b` field to Set
    pub struct SetSubjectB<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubjectB<S> {}
    impl<S: State> State for SetSubjectB<S> {
        type SubjectB = Set<members::subject_b>;
        type Direction = S::Direction;
        type CreatedAt = S::CreatedAt;
        type SubjectA = S::SubjectA;
        type InteractionType = S::InteractionType;
    }
    ///State transition - sets the `direction` field to Set
    pub struct SetDirection<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDirection<S> {}
    impl<S: State> State for SetDirection<S> {
        type SubjectB = S::SubjectB;
        type Direction = Set<members::direction>;
        type CreatedAt = S::CreatedAt;
        type SubjectA = S::SubjectA;
        type InteractionType = S::InteractionType;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type SubjectB = S::SubjectB;
        type Direction = S::Direction;
        type CreatedAt = Set<members::created_at>;
        type SubjectA = S::SubjectA;
        type InteractionType = S::InteractionType;
    }
    ///State transition - sets the `subject_a` field to Set
    pub struct SetSubjectA<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubjectA<S> {}
    impl<S: State> State for SetSubjectA<S> {
        type SubjectB = S::SubjectB;
        type Direction = S::Direction;
        type CreatedAt = S::CreatedAt;
        type SubjectA = Set<members::subject_a>;
        type InteractionType = S::InteractionType;
    }
    ///State transition - sets the `interaction_type` field to Set
    pub struct SetInteractionType<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetInteractionType<S> {}
    impl<S: State> State for SetInteractionType<S> {
        type SubjectB = S::SubjectB;
        type Direction = S::Direction;
        type CreatedAt = S::CreatedAt;
        type SubjectA = S::SubjectA;
        type InteractionType = Set<members::interaction_type>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `subject_b` field
        pub struct subject_b(());
        ///Marker type for the `direction` field
        pub struct direction(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `subject_a` field
        pub struct subject_a(());
        ///Marker type for the `interaction_type` field
        pub struct interaction_type(());
    }
}

/// Builder for constructing an instance of this type
pub struct InteractionBuilder<'a, S: interaction_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<
            crate::org_rwell::test::interaction::InteractionSubject<'a>,
        >,
        ::core::option::Option<
            crate::org_rwell::test::interaction::InteractionSubject<'a>,
        >,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Interaction<'a> {
    /// Create a new builder for this type
    pub fn new() -> InteractionBuilder<'a, interaction_state::Empty> {
        InteractionBuilder::new()
    }
}

impl<'a> InteractionBuilder<'a, interaction_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: interaction_state::State> InteractionBuilder<'a, S> {
    /// Set the `comment` field (optional)
    pub fn comment(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `comment` field to an Option value (optional)
    pub fn maybe_comment(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: interaction_state::State> InteractionBuilder<'a, S> {
    /// Set the `confidence` field (optional)
    pub fn confidence(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `confidence` field to an Option value (optional)
    pub fn maybe_confidence(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::CreatedAt: interaction_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> InteractionBuilder<'a, interaction_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::Direction: interaction_state::IsUnset,
{
    /// Set the `direction` field (required)
    pub fn direction(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> InteractionBuilder<'a, interaction_state::SetDirection<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::InteractionType: interaction_state::IsUnset,
{
    /// Set the `interactionType` field (required)
    pub fn interaction_type(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> InteractionBuilder<'a, interaction_state::SetInteractionType<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::SubjectA: interaction_state::IsUnset,
{
    /// Set the `subjectA` field (required)
    pub fn subject_a(
        mut self,
        value: impl Into<crate::org_rwell::test::interaction::InteractionSubject<'a>>,
    ) -> InteractionBuilder<'a, interaction_state::SetSubjectA<S>> {
        self.__unsafe_private_named.5 = ::core::option::Option::Some(value.into());
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::SubjectB: interaction_state::IsUnset,
{
    /// Set the `subjectB` field (required)
    pub fn subject_b(
        mut self,
        value: impl Into<crate::org_rwell::test::interaction::InteractionSubject<'a>>,
    ) -> InteractionBuilder<'a, interaction_state::SetSubjectB<S>> {
        self.__unsafe_private_named.6 = ::core::option::Option::Some(value.into());
        InteractionBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> InteractionBuilder<'a, S>
where
    S: interaction_state::State,
    S::SubjectB: interaction_state::IsSet,
    S::Direction: interaction_state::IsSet,
    S::CreatedAt: interaction_state::IsSet,
    S::SubjectA: interaction_state::IsSet,
    S::InteractionType: interaction_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Interaction<'a> {
        Interaction {
            comment: self.__unsafe_private_named.0,
            confidence: self.__unsafe_private_named.1,
            created_at: self.__unsafe_private_named.2.unwrap(),
            direction: self.__unsafe_private_named.3.unwrap(),
            interaction_type: self.__unsafe_private_named.4.unwrap(),
            subject_a: self.__unsafe_private_named.5.unwrap(),
            subject_b: self.__unsafe_private_named.6.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Interaction<'a> {
        Interaction {
            comment: self.__unsafe_private_named.0,
            confidence: self.__unsafe_private_named.1,
            created_at: self.__unsafe_private_named.2.unwrap(),
            direction: self.__unsafe_private_named.3.unwrap(),
            interaction_type: self.__unsafe_private_named.4.unwrap(),
            subject_a: self.__unsafe_private_named.5.unwrap(),
            subject_b: self.__unsafe_private_named.6.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Interaction<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, InteractionRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct InteractionGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Interaction<'a>,
}

impl From<InteractionGetRecordOutput<'_>> for Interaction<'_> {
    fn from(output: InteractionGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Interaction<'_> {
    const NSID: &'static str = "org.rwell.test.interaction";
    type Record = InteractionRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct InteractionRecord;
impl jacquard_common::xrpc::XrpcResp for InteractionRecord {
    const NSID: &'static str = "org.rwell.test.interaction";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = InteractionGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for InteractionRecord {
    const NSID: &'static str = "org.rwell.test.interaction";
    type Record = InteractionRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Interaction<'a> {
    fn nsid() -> &'static str {
        "org.rwell.test.interaction"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_org_rwell_test_interaction()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        if let Some(ref value) = self.comment {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(::jacquard_lexicon::validation::ConstraintError::MaxLength {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "comment",
                    ),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.interaction_type;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(::jacquard_lexicon::validation::ConstraintError::MaxLength {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "interaction_type",
                    ),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}