#!/usr/bin/env node

/**
 * Generate AT Protocol types from lexicon definitions.
 *
 * This script:
 * 1. Finds all lexicon JSON files
 * 2. Runs lex gen-api to generate TypeScript types
 * 3. Fixes the generated types to remove unused dependencies
 */

import { execSync } from 'child_process';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const lexiconsDir = join(rootDir, 'lexicons');
const generatedDir = join(rootDir, 'packages/biosky-appview/src/generated');

// Find all lexicon JSON files
function findLexiconFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...findLexiconFiles(fullPath));
    } else if (entry.name.endsWith('.json')) {
      files.push(fullPath);
    }
  }
  return files;
}

const lexiconFiles = findLexiconFiles(lexiconsDir);
console.log(`Found ${lexiconFiles.length} lexicon files`);

// Run lex gen-api
const cmd = `npx lex gen-api --yes ${generatedDir} ${lexiconFiles.join(' ')}`;
console.log('Running:', cmd);
execSync(cmd, { stdio: 'inherit', cwd: rootDir });

// Fix index.ts - simplify to only export types
const indexPath = join(generatedDir, 'index.ts');
const simplifiedIndex = `/**
 * GENERATED CODE - DO NOT MODIFY
 *
 * Note: This file has been simplified to only export type definitions.
 * The full client code is generated by \`lex gen-api\` but requires AT Protocol
 * dependencies that are not used in this project.
 */

export * as OrgRwellTestIdentification from './types/org/rwell/test/identification.js'
export * as OrgRwellTestLike from './types/org/rwell/test/like.js'
export * as OrgRwellTestOccurrence from './types/org/rwell/test/occurrence.js'

export { schemas, lexicons, ids } from './lexicons.js'
export type { $Typed, Un$Typed, OmitKey } from './util.js'
`;
writeFileSync(indexPath, simplifiedIndex);
console.log('Fixed: index.ts');

// Fix identification.ts - remove CID import and inline StrongRef
const identificationPath = join(generatedDir, 'types/org/rwell/test/identification.ts');
let identificationContent = readFileSync(identificationPath, 'utf-8');

// Remove CID import and fix other imports
identificationContent = identificationContent
  .replace(/import { type ValidationResult, BlobRef } from '@atproto\/lexicon'\n/, `import { type BlobRef } from '@atproto/lexicon'\n`)
  .replace(/import { CID } from 'multiformats\/cid'\n/, '')
  .replace(/import { validate as _validate } from '\.\.\/\.\.\/\.\.\/\.\.\/lexicons'/, `import { validate as _validate } from '../../../../lexicons.js'`)
  .replace(/import \{\n  type \$Typed,\n  is\$typed as _is\$typed,\n  type OmitKey,\n\} from '\.\.\/\.\.\/\.\.\/\.\.\/util'/, `import {\n  is$typed as _is$typed,\n} from '../../../../util.js'`)
  .replace(/import type \* as ComAtprotoRepoStrongRef from '\.\.\/\.\.\/\.\.\/com\/atproto\/repo\/strongRef\.js'\n/, '')
  .replace(/subject: ComAtprotoRepoStrongRef\.Main/, 'subject: StrongRef');

// Add StrongRef interface after imports
const strongRefInterface = `
/** A reference to a specific version of a record (AT Protocol strong ref). */
interface StrongRef {
  uri: string
  cid: string
}
`;

// Insert StrongRef after the last import line
const lines = identificationContent.split('\n');
let lastImportIndex = -1;
for (let i = 0; i < lines.length; i++) {
  if (lines[i].startsWith('import ') || lines[i].startsWith('} from ')) {
    lastImportIndex = i;
  }
}
if (lastImportIndex !== -1) {
  lines.splice(lastImportIndex + 1, 0, strongRefInterface);
  identificationContent = lines.join('\n');
}

writeFileSync(identificationPath, identificationContent);
console.log('Fixed: identification.ts');

// Fix occurrence.ts - remove CID import and fix imports
const occurrencePath = join(generatedDir, 'types/org/rwell/test/occurrence.ts');
let occurrenceContent = readFileSync(occurrencePath, 'utf-8');

occurrenceContent = occurrenceContent
  .replace(/import { type ValidationResult, BlobRef } from '@atproto\/lexicon'\n/, `import { type BlobRef } from '@atproto/lexicon'\n`)
  .replace(/import { CID } from 'multiformats\/cid'\n/, '')
  .replace(/import { validate as _validate } from '\.\.\/\.\.\/\.\.\/\.\.\/lexicons'/, `import { validate as _validate } from '../../../../lexicons.js'`)
  .replace(/import \{\n  type \$Typed,\n  is\$typed as _is\$typed,\n  type OmitKey,\n\} from '\.\.\/\.\.\/\.\.\/\.\.\/util'/, `import {\n  is$typed as _is$typed,\n} from '../../../../util.js'`);

writeFileSync(occurrencePath, occurrenceContent);
console.log('Fixed: occurrence.ts');

// Fix like.ts - remove CID import, fix imports, and inline StrongRef
const likePath = join(generatedDir, 'types/org/rwell/test/like.ts');
let likeContent = readFileSync(likePath, 'utf-8');

likeContent = likeContent
  .replace(/import { type ValidationResult, BlobRef } from '@atproto\/lexicon'\n/, `import { type BlobRef } from '@atproto/lexicon'\n`)
  .replace(/import { CID } from 'multiformats\/cid'\n/, '')
  .replace(/import { validate as _validate } from '\.\.\/\.\.\/\.\.\/\.\.\/lexicons'/, `import { validate as _validate } from '../../../../lexicons.js'`)
  .replace(/import \{\n  type \$Typed,\n  is\$typed as _is\$typed,\n  type OmitKey,\n\} from '\.\.\/\.\.\/\.\.\/\.\.\/util'/, `import {\n  is$typed as _is$typed,\n} from '../../../../util.js'`)
  .replace(/import type \* as ComAtprotoRepoStrongRef from '\.\.\/\.\.\/\.\.\/com\/atproto\/repo\/strongRef\.js'\n/, '')
  .replace(/subject: ComAtprotoRepoStrongRef\.Main/, 'subject: StrongRef');

// Add StrongRef interface after imports for like.ts
const likeLines = likeContent.split('\n');
let likeLastImportIndex = -1;
for (let i = 0; i < likeLines.length; i++) {
  if (likeLines[i].startsWith('import ') || likeLines[i].startsWith('} from ')) {
    likeLastImportIndex = i;
  }
}
if (likeLastImportIndex !== -1) {
  likeLines.splice(likeLastImportIndex + 1, 0, strongRefInterface);
  likeContent = likeLines.join('\n');
}

writeFileSync(likePath, likeContent);
console.log('Fixed: like.ts');

// Fix comment.ts - remove CID import, fix imports, and inline StrongRef
const commentPath = join(generatedDir, 'types/org/rwell/test/comment.ts');
let commentContent = readFileSync(commentPath, 'utf-8');

commentContent = commentContent
  .replace(/import { type ValidationResult, BlobRef } from '@atproto\/lexicon'\n/, `import { type BlobRef } from '@atproto/lexicon'\n`)
  .replace(/import { CID } from 'multiformats\/cid'\n/, '')
  .replace(/import { validate as _validate } from '\.\.\/\.\.\/\.\.\/\.\.\/lexicons'/, `import { validate as _validate } from '../../../../lexicons.js'`)
  .replace(/import \{\n  type \$Typed,\n  is\$typed as _is\$typed,\n  type OmitKey,\n\} from '\.\.\/\.\.\/\.\.\/\.\.\/util'/, `import {\n  is$typed as _is$typed,\n} from '../../../../util.js'`)
  .replace(/import type \* as ComAtprotoRepoStrongRef from '\.\.\/\.\.\/\.\.\/com\/atproto\/repo\/strongRef\.js'\n/, '')
  .replace(/subject: ComAtprotoRepoStrongRef\.Main/g, 'subject: StrongRef')
  .replace(/replyTo\?: ComAtprotoRepoStrongRef\.Main/g, 'replyTo?: StrongRef');

// Add StrongRef interface after imports for comment.ts
const commentLines = commentContent.split('\n');
let commentLastImportIndex = -1;
for (let i = 0; i < commentLines.length; i++) {
  if (commentLines[i].startsWith('import ') || commentLines[i].startsWith('} from ')) {
    commentLastImportIndex = i;
  }
}
if (commentLastImportIndex !== -1) {
  commentLines.splice(commentLastImportIndex + 1, 0, strongRefInterface);
  commentContent = commentLines.join('\n');
}

writeFileSync(commentPath, commentContent);
console.log('Fixed: comment.ts');

console.log('All generated types fixed!');
