#!/usr/bin/env node

/**
 * Generate AT Protocol types from lexicon definitions.
 *
 * Uses @atproto/lex (ts-lex) to generate TypeScript types for both packages.
 */

import { execSync } from 'child_process';
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const packages = [
  'packages/observing-appview/src/generated',
  'packages/observing-shared/src/generated',
];

// Generate types for each package
for (const outDir of packages) {
  console.log(`Generating types in ${outDir}...`);
  execSync(
    `npx ts-lex build --lexicons ./lexicons --out ./${outDir} --clear --indexFile`,
    { stdio: 'inherit', cwd: rootDir }
  );
}

// Add @ts-nocheck to .defs.ts files to work around library type inference issues
// The generated code is correct at runtime, but TypeScript has issues with optional field inference
function addTsNocheck(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      addTsNocheck(fullPath);
    } else if (entry.name.endsWith('.defs.ts')) {
      let content = readFileSync(fullPath, 'utf-8');
      // Add @ts-nocheck after the header comment
      content = content.replace(
        '/*\n * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.\n */',
        '/*\n * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.\n */\n// @ts-nocheck'
      );
      writeFileSync(fullPath, content);
      console.log(`Fixed: ${fullPath}`);
    }
  }
}

for (const outDir of packages) {
  addTsNocheck(join(rootDir, outDir));
}

console.log('All types generated!');
