// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.identification
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::com_atproto::repo::strong_ref::StrongRef;
/// An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "bio.lexicons.temp.identification",
    tag = "$type"
)]
pub struct Identification<'a> {
    ///Taxonomic class (Darwin Core dwc:class).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub class: Option<CowStr<'a>>,
    ///Taxonomic family (Darwin Core dwc:family).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub family: Option<CowStr<'a>>,
    ///Taxonomic genus (Darwin Core dwc:genus).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub genus: Option<CowStr<'a>>,
    ///Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub identification_remarks: Option<CowStr<'a>>,
    ///Taxonomic kingdom (Darwin Core dwc:kingdom).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub kingdom: Option<CowStr<'a>>,
    ///Taxonomic order (Darwin Core dwc:order).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub order: Option<CowStr<'a>>,
    ///Taxonomic phylum (Darwin Core dwc:phylum).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub phylum: Option<CowStr<'a>>,
    ///The full scientific name (Darwin Core dwc:scientificName).
    #[serde(borrow)]
    pub scientific_name: CowStr<'a>,
    ///The authorship information for the scientificName (Darwin Core dwc:scientificNameAuthorship).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub scientific_name_authorship: Option<CowStr<'a>>,
    ///A strong reference (CID + URI) to the observation being identified.
    #[serde(borrow)]
    pub subject: StrongRef<'a>,
    ///The taxonomic rank of the identification (Darwin Core dwc:taxonRank).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub taxon_rank: Option<IdentificationTaxonRank<'a>>,
    ///Common name for the taxon in the identifier's language (Darwin Core dwc:vernacularName).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub vernacular_name: Option<CowStr<'a>>,
}

/// The taxonomic rank of the identification (Darwin Core dwc:taxonRank).

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum IdentificationTaxonRank<'a> {
    Kingdom,
    Phylum,
    Class,
    Order,
    Family,
    Genus,
    Species,
    Subspecies,
    Variety,
    Form,
    Other(CowStr<'a>),
}

impl<'a> IdentificationTaxonRank<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Kingdom => "kingdom",
            Self::Phylum => "phylum",
            Self::Class => "class",
            Self::Order => "order",
            Self::Family => "family",
            Self::Genus => "genus",
            Self::Species => "species",
            Self::Subspecies => "subspecies",
            Self::Variety => "variety",
            Self::Form => "form",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for IdentificationTaxonRank<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "kingdom" => Self::Kingdom,
            "phylum" => Self::Phylum,
            "class" => Self::Class,
            "order" => Self::Order,
            "family" => Self::Family,
            "genus" => Self::Genus,
            "species" => Self::Species,
            "subspecies" => Self::Subspecies,
            "variety" => Self::Variety,
            "form" => Self::Form,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for IdentificationTaxonRank<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "kingdom" => Self::Kingdom,
            "phylum" => Self::Phylum,
            "class" => Self::Class,
            "order" => Self::Order,
            "family" => Self::Family,
            "genus" => Self::Genus,
            "species" => Self::Species,
            "subspecies" => Self::Subspecies,
            "variety" => Self::Variety,
            "form" => Self::Form,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for IdentificationTaxonRank<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for IdentificationTaxonRank<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for IdentificationTaxonRank<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for IdentificationTaxonRank<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for IdentificationTaxonRank<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for IdentificationTaxonRank<'_> {
    type Output = IdentificationTaxonRank<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            IdentificationTaxonRank::Kingdom => IdentificationTaxonRank::Kingdom,
            IdentificationTaxonRank::Phylum => IdentificationTaxonRank::Phylum,
            IdentificationTaxonRank::Class => IdentificationTaxonRank::Class,
            IdentificationTaxonRank::Order => IdentificationTaxonRank::Order,
            IdentificationTaxonRank::Family => IdentificationTaxonRank::Family,
            IdentificationTaxonRank::Genus => IdentificationTaxonRank::Genus,
            IdentificationTaxonRank::Species => IdentificationTaxonRank::Species,
            IdentificationTaxonRank::Subspecies => IdentificationTaxonRank::Subspecies,
            IdentificationTaxonRank::Variety => IdentificationTaxonRank::Variety,
            IdentificationTaxonRank::Form => IdentificationTaxonRank::Form,
            IdentificationTaxonRank::Other(v) => {
                IdentificationTaxonRank::Other(v.into_static())
            }
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct IdentificationGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Identification<'a>,
}

impl<'a> Identification<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, IdentificationRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentificationRecord;
impl XrpcResp for IdentificationRecord {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = IdentificationGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<IdentificationGetRecordOutput<'_>> for Identification<'_> {
    fn from(output: IdentificationGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Identification<'_> {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    type Record = IdentificationRecord;
}

impl Collection for IdentificationRecord {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    type Record = IdentificationRecord;
}

impl<'a> LexiconSchema for Identification<'a> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.identification"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_identification()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.class {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("class"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.family {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("family"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.genus {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("genus"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.identification_remarks {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("identification_remarks"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.kingdom {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("kingdom"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.order {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("order"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.phylum {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("phylum"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.scientific_name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("scientific_name"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.scientific_name_authorship {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("scientific_name_authorship"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.taxon_rank {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("taxon_rank"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.vernacular_name {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("vernacular_name"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod identification_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type ScientificName;
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type ScientificName = Unset;
        type Subject = Unset;
    }
    ///State transition - sets the `scientific_name` field to Set
    pub struct SetScientificName<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetScientificName<S> {}
    impl<S: State> State for SetScientificName<S> {
        type ScientificName = Set<members::scientific_name>;
        type Subject = S::Subject;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubject<S> {}
    impl<S: State> State for SetSubject<S> {
        type ScientificName = S::ScientificName;
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `scientific_name` field
        pub struct scientific_name(());
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type
pub struct IdentificationBuilder<'a, S: identification_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<StrongRef<'a>>,
        Option<IdentificationTaxonRank<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Identification<'a> {
    /// Create a new builder for this type
    pub fn new() -> IdentificationBuilder<'a, identification_state::Empty> {
        IdentificationBuilder::new()
    }
}

impl<'a> IdentificationBuilder<'a, identification_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        IdentificationBuilder {
            _state: PhantomData,
            _fields: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `class` field (optional)
    pub fn class(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `class` field to an Option value (optional)
    pub fn maybe_class(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `family` field (optional)
    pub fn family(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `family` field to an Option value (optional)
    pub fn maybe_family(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `genus` field (optional)
    pub fn genus(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `genus` field to an Option value (optional)
    pub fn maybe_genus(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `identificationRemarks` field (optional)
    pub fn identification_remarks(
        mut self,
        value: impl Into<Option<CowStr<'a>>>,
    ) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `identificationRemarks` field to an Option value (optional)
    pub fn maybe_identification_remarks(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `kingdom` field (optional)
    pub fn kingdom(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `kingdom` field to an Option value (optional)
    pub fn maybe_kingdom(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `order` field (optional)
    pub fn order(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `order` field to an Option value (optional)
    pub fn maybe_order(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `phylum` field (optional)
    pub fn phylum(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `phylum` field to an Option value (optional)
    pub fn maybe_phylum(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<'a, S> IdentificationBuilder<'a, S>
where
    S: identification_state::State,
    S::ScientificName: identification_state::IsUnset,
{
    /// Set the `scientificName` field (required)
    pub fn scientific_name(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> IdentificationBuilder<'a, identification_state::SetScientificName<S>> {
        self._fields.7 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `scientificNameAuthorship` field (optional)
    pub fn scientific_name_authorship(
        mut self,
        value: impl Into<Option<CowStr<'a>>>,
    ) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `scientificNameAuthorship` field to an Option value (optional)
    pub fn maybe_scientific_name_authorship(
        mut self,
        value: Option<CowStr<'a>>,
    ) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<'a, S> IdentificationBuilder<'a, S>
where
    S: identification_state::State,
    S::Subject: identification_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<StrongRef<'a>>,
    ) -> IdentificationBuilder<'a, identification_state::SetSubject<S>> {
        self._fields.9 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `taxonRank` field (optional)
    pub fn taxon_rank(
        mut self,
        value: impl Into<Option<IdentificationTaxonRank<'a>>>,
    ) -> Self {
        self._fields.10 = value.into();
        self
    }
    /// Set the `taxonRank` field to an Option value (optional)
    pub fn maybe_taxon_rank(
        mut self,
        value: Option<IdentificationTaxonRank<'a>>,
    ) -> Self {
        self._fields.10 = value;
        self
    }
}

impl<'a, S: identification_state::State> IdentificationBuilder<'a, S> {
    /// Set the `vernacularName` field (optional)
    pub fn vernacular_name(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.11 = value.into();
        self
    }
    /// Set the `vernacularName` field to an Option value (optional)
    pub fn maybe_vernacular_name(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.11 = value;
        self
    }
}

impl<'a, S> IdentificationBuilder<'a, S>
where
    S: identification_state::State,
    S::ScientificName: identification_state::IsSet,
    S::Subject: identification_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Identification<'a> {
        Identification {
            class: self._fields.0,
            family: self._fields.1,
            genus: self._fields.2,
            identification_remarks: self._fields.3,
            kingdom: self._fields.4,
            order: self._fields.5,
            phylum: self._fields.6,
            scientific_name: self._fields.7.unwrap(),
            scientific_name_authorship: self._fields.8,
            subject: self._fields.9.unwrap(),
            taxon_rank: self._fields.10,
            vernacular_name: self._fields.11,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Identification<'a> {
        Identification {
            class: self._fields.0,
            family: self._fields.1,
            genus: self._fields.2,
            identification_remarks: self._fields.3,
            kingdom: self._fields.4,
            order: self._fields.5,
            phylum: self._fields.6,
            scientific_name: self._fields.7.unwrap(),
            scientific_name_authorship: self._fields.8,
            subject: self._fields.9.unwrap(),
            taxon_rank: self._fields.10,
            vernacular_name: self._fields.11,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_bio_lexicons_temp_identification() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("bio.lexicons.temp.identification"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("subject"),
                                SmolStr::new_static("scientificName")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("class"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic class (Darwin Core dwc:class).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("family"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic family (Darwin Core dwc:family).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("genus"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic genus (Darwin Core dwc:genus).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("identificationRemarks"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).",
                                        ),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("kingdom"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic kingdom (Darwin Core dwc:kingdom).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("order"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic order (Darwin Core dwc:order).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("phylum"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic phylum (Darwin Core dwc:phylum).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("scientificName"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The full scientific name (Darwin Core dwc:scientificName).",
                                        ),
                                    ),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("scientificNameAuthorship"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The authorship information for the scientificName (Darwin Core dwc:scientificNameAuthorship).",
                                        ),
                                    ),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("taxonRank"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The taxonomic rank of the identification (Darwin Core dwc:taxonRank).",
                                        ),
                                    ),
                                    max_length: Some(32usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("vernacularName"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Common name for the taxon in the identifier's language (Darwin Core dwc:vernacularName).",
                                        ),
                                    ),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}