// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.identification
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "bio.lexicons.temp.identification",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Identification<S: BosStr = DefaultStr> {
    ///Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identification_remarks: Option<S>,
    ///Taxonomic kingdom for disambiguating homonyms (Darwin Core dwc:kingdom).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub kingdom: Option<S>,
    ///A strong reference (CID + URI) to the occurrence being identified.
    pub occurrence: StrongRef<S>,
    ///The full scientific name, with authorship and date information if known (Darwin Core dwc:scientificName).
    pub scientific_name: S,
    ///The taxonomic rank of the identification (Darwin Core dwc:taxonRank).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxon_rank: Option<IdentificationTaxonRank<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// The taxonomic rank of the identification (Darwin Core dwc:taxonRank).

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum IdentificationTaxonRank<S: BosStr = DefaultStr> {
    Kingdom,
    Phylum,
    Class,
    Order,
    Family,
    Genus,
    Species,
    Subspecies,
    Variety,
    Form,
    Other(S),
}

impl<S: BosStr> IdentificationTaxonRank<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Kingdom => "kingdom",
            Self::Phylum => "phylum",
            Self::Class => "class",
            Self::Order => "order",
            Self::Family => "family",
            Self::Genus => "genus",
            Self::Species => "species",
            Self::Subspecies => "subspecies",
            Self::Variety => "variety",
            Self::Form => "form",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "kingdom" => Self::Kingdom,
            "phylum" => Self::Phylum,
            "class" => Self::Class,
            "order" => Self::Order,
            "family" => Self::Family,
            "genus" => Self::Genus,
            "species" => Self::Species,
            "subspecies" => Self::Subspecies,
            "variety" => Self::Variety,
            "form" => Self::Form,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for IdentificationTaxonRank<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for IdentificationTaxonRank<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for IdentificationTaxonRank<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for IdentificationTaxonRank<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for IdentificationTaxonRank<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for IdentificationTaxonRank<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = IdentificationTaxonRank<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            IdentificationTaxonRank::Kingdom => IdentificationTaxonRank::Kingdom,
            IdentificationTaxonRank::Phylum => IdentificationTaxonRank::Phylum,
            IdentificationTaxonRank::Class => IdentificationTaxonRank::Class,
            IdentificationTaxonRank::Order => IdentificationTaxonRank::Order,
            IdentificationTaxonRank::Family => IdentificationTaxonRank::Family,
            IdentificationTaxonRank::Genus => IdentificationTaxonRank::Genus,
            IdentificationTaxonRank::Species => IdentificationTaxonRank::Species,
            IdentificationTaxonRank::Subspecies => IdentificationTaxonRank::Subspecies,
            IdentificationTaxonRank::Variety => IdentificationTaxonRank::Variety,
            IdentificationTaxonRank::Form => IdentificationTaxonRank::Form,
            IdentificationTaxonRank::Other(v) => IdentificationTaxonRank::Other(v.into_static()),
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct IdentificationGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Identification<S>,
}

impl<S: BosStr> Identification<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, IdentificationRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct IdentificationRecord;
impl XrpcResp for IdentificationRecord {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = IdentificationGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<IdentificationGetRecordOutput<S>> for Identification<S> {
    fn from(output: IdentificationGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Identification<S> {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    type Record = IdentificationRecord;
}

impl Collection for IdentificationRecord {
    const NSID: &'static str = "bio.lexicons.temp.identification";
    type Record = IdentificationRecord;
}

impl<S: BosStr> LexiconSchema for Identification<S> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.identification"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_identification()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.identification_remarks {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("identification_remarks"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.kingdom {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("kingdom"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.scientific_name;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 256usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("scientific_name"),
                    max: 256usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.taxon_rank {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("taxon_rank"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod identification_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Occurrence;
        type ScientificName;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Occurrence = Unset;
        type ScientificName = Unset;
    }
    ///State transition - sets the `occurrence` field to Set
    pub struct SetOccurrence<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetOccurrence<St> {}
    impl<St: State> State for SetOccurrence<St> {
        type Occurrence = Set<members::occurrence>;
        type ScientificName = St::ScientificName;
    }
    ///State transition - sets the `scientific_name` field to Set
    pub struct SetScientificName<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetScientificName<St> {}
    impl<St: State> State for SetScientificName<St> {
        type Occurrence = St::Occurrence;
        type ScientificName = Set<members::scientific_name>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `occurrence` field
        pub struct occurrence(());
        ///Marker type for the `scientific_name` field
        pub struct scientific_name(());
    }
}

/// Builder for constructing an instance of this type.
pub struct IdentificationBuilder<S: BosStr, St: identification_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<S>,
        Option<StrongRef<S>>,
        Option<S>,
        Option<IdentificationTaxonRank<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> Identification<S> {
    /// Create a new builder for this type.
    pub fn new() -> IdentificationBuilder<S, identification_state::Empty> {
        IdentificationBuilder::new()
    }
}

impl<S: BosStr> IdentificationBuilder<S, identification_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        IdentificationBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `identificationRemarks` field (optional)
    pub fn identification_remarks(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `identificationRemarks` field to an Option value (optional)
    pub fn maybe_identification_remarks(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `kingdom` field (optional)
    pub fn kingdom(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `kingdom` field to an Option value (optional)
    pub fn maybe_kingdom(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::Occurrence: identification_state::IsUnset,
{
    /// Set the `occurrence` field (required)
    pub fn occurrence(
        mut self,
        value: impl Into<StrongRef<S>>,
    ) -> IdentificationBuilder<S, identification_state::SetOccurrence<St>> {
        self._fields.2 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::ScientificName: identification_state::IsUnset,
{
    /// Set the `scientificName` field (required)
    pub fn scientific_name(
        mut self,
        value: impl Into<S>,
    ) -> IdentificationBuilder<S, identification_state::SetScientificName<St>> {
        self._fields.3 = Option::Some(value.into());
        IdentificationBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: identification_state::State> IdentificationBuilder<S, St> {
    /// Set the `taxonRank` field (optional)
    pub fn taxon_rank(mut self, value: impl Into<Option<IdentificationTaxonRank<S>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `taxonRank` field to an Option value (optional)
    pub fn maybe_taxon_rank(mut self, value: Option<IdentificationTaxonRank<S>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<S: BosStr, St> IdentificationBuilder<S, St>
where
    St: identification_state::State,
    St::Occurrence: identification_state::IsSet,
    St::ScientificName: identification_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Identification<S> {
        Identification {
            identification_remarks: self._fields.0,
            kingdom: self._fields.1,
            occurrence: self._fields.2.unwrap(),
            scientific_name: self._fields.3.unwrap(),
            taxon_rank: self._fields.4,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Identification<S> {
        Identification {
            identification_remarks: self._fields.0,
            kingdom: self._fields.1,
            occurrence: self._fields.2.unwrap(),
            scientific_name: self._fields.3.unwrap(),
            taxon_rank: self._fields.4,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_bio_lexicons_temp_identification() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("bio.lexicons.temp.identification"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "An identification suggestion for an existing observation. Used to propose or agree with a taxonomic identification.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("occurrence"),
                                SmolStr::new_static("scientificName")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("identificationRemarks"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Explanation or reasoning for this identification (Darwin Core dwc:identificationRemarks).",
                                        ),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("kingdom"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Taxonomic kingdom for disambiguating homonyms (Darwin Core dwc:kingdom).",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("occurrence"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("scientificName"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The full scientific name, with authorship and date information if known (Darwin Core dwc:scientificName).",
                                        ),
                                    ),
                                    max_length: Some(256usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("taxonRank"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The taxonomic rank of the identification (Darwin Core dwc:taxonRank).",
                                        ),
                                    ),
                                    max_length: Some(32usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
