// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.occurrence
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "bio.lexicons.temp.occurrence",
    tag = "$type"
)]
pub struct Occurrence<'a> {
    ///Strong references to media records documenting the observation (Darwin Core dwc:associatedMedia).
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub associated_media: Option<Vec<StrongRef<'a>>>,
    ///The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location (Darwin Core dwc:coordinateUncertaintyInMeters).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coordinate_uncertainty_in_meters: Option<i64>,
    ///The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub decimal_latitude: Option<CowStr<'a>>,
    ///The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub decimal_longitude: Option<CowStr<'a>>,
    ///The date-time when the observation occurred, in ISO 8601 format (Darwin Core dwc:eventDate).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_date: Option<Datetime>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct OccurrenceGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Occurrence<'a>,
}

impl<'a> Occurrence<'a> {
    pub fn uri(uri: impl Into<CowStr<'a>>) -> Result<RecordUri<'a, OccurrenceRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct OccurrenceRecord;
impl XrpcResp for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = OccurrenceGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<OccurrenceGetRecordOutput<'_>> for Occurrence<'_> {
    fn from(output: OccurrenceGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Occurrence<'_> {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    type Record = OccurrenceRecord;
}

impl Collection for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    type Record = OccurrenceRecord;
}

impl<'a> LexiconSchema for Occurrence<'a> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.occurrence"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_occurrence()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.associated_media {
            #[allow(unused_comparisons)]
            if value.len() > 10usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("associated_media"),
                    max: 10usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.coordinate_uncertainty_in_meters {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("coordinate_uncertainty_in_meters"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod occurrence_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct OccurrenceBuilder<'a, S: occurrence_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<Vec<StrongRef<'a>>>,
        Option<i64>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<Datetime>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Occurrence<'a> {
    /// Create a new builder for this type
    pub fn new() -> OccurrenceBuilder<'a, occurrence_state::Empty> {
        OccurrenceBuilder::new()
    }
}

impl<'a> OccurrenceBuilder<'a, occurrence_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        OccurrenceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `associatedMedia` field (optional)
    pub fn associated_media(mut self, value: impl Into<Option<Vec<StrongRef<'a>>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `associatedMedia` field to an Option value (optional)
    pub fn maybe_associated_media(mut self, value: Option<Vec<StrongRef<'a>>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `coordinateUncertaintyInMeters` field (optional)
    pub fn coordinate_uncertainty_in_meters(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `coordinateUncertaintyInMeters` field to an Option value (optional)
    pub fn maybe_coordinate_uncertainty_in_meters(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `decimalLatitude` field (optional)
    pub fn decimal_latitude(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `decimalLatitude` field to an Option value (optional)
    pub fn maybe_decimal_latitude(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `decimalLongitude` field (optional)
    pub fn decimal_longitude(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `decimalLongitude` field to an Option value (optional)
    pub fn maybe_decimal_longitude(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `eventDate` field (optional)
    pub fn event_date(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `eventDate` field to an Option value (optional)
    pub fn maybe_event_date(mut self, value: Option<Datetime>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<'a, S> OccurrenceBuilder<'a, S>
where
    S: occurrence_state::State,
{
    /// Build the final struct
    pub fn build(self) -> Occurrence<'a> {
        Occurrence {
            associated_media: self._fields.0,
            coordinate_uncertainty_in_meters: self._fields.1,
            decimal_latitude: self._fields.2,
            decimal_longitude: self._fields.3,
            event_date: self._fields.4,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Occurrence<'a> {
        Occurrence {
            associated_media: self._fields.0,
            coordinate_uncertainty_in_meters: self._fields.1,
            decimal_latitude: self._fields.2,
            decimal_longitude: self._fields.3,
            event_date: self._fields.4,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_bio_lexicons_temp_occurrence() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("bio.lexicons.temp.occurrence"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("associatedMedia"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Strong references to media records documenting the observation (Darwin Core dwc:associatedMedia).",
                                        ),
                                    ),
                                    items: LexArrayItem::Ref(LexRef {
                                        r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                        ..Default::default()
                                    }),
                                    max_length: Some(10usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("coordinateUncertaintyInMeters"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("decimalLatitude"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("decimalLongitude"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("eventDate"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The date-time when the observation occurred, in ISO 8601 format (Darwin Core dwc:eventDate).",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
