// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.occurrence
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, jacquard_derive::IntoStatic,
)]
#[serde(rename_all = "camelCase")]
pub struct Occurrence<'a> {
    /// Strong references to media records documenting the observation (Darwin Core dwc:associatedMedia).
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub associated_media:
        std::option::Option<Vec<crate::com_atproto::repo::strong_ref::StrongRef<'a>>>,
    /// The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location (Darwin Core dwc:coordinateUncertaintyInMeters).
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub coordinate_uncertainty_in_meters: std::option::Option<i64>,
    /// The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub decimal_latitude: std::option::Option<jacquard_common::CowStr<'a>>,
    /// The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub decimal_longitude: std::option::Option<jacquard_common::CowStr<'a>>,
    /// The date-time when the observation occurred, in ISO 8601 format (Darwin Core dwc:eventDate).
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub event_date: std::option::Option<jacquard_common::types::string::Datetime>,
}

pub mod occurrence_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct OccurrenceBuilder<'a, S: occurrence_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<Vec<crate::com_atproto::repo::strong_ref::StrongRef<'a>>>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Occurrence<'a> {
    /// Create a new builder for this type
    pub fn new() -> OccurrenceBuilder<'a, occurrence_state::Empty> {
        OccurrenceBuilder::new()
    }
}

impl<'a> OccurrenceBuilder<'a, occurrence_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        OccurrenceBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `associatedMedia` field (optional)
    pub fn associated_media(
        mut self,
        value: impl Into<Option<Vec<crate::com_atproto::repo::strong_ref::StrongRef<'a>>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `associatedMedia` field to an Option value (optional)
    pub fn maybe_associated_media(
        mut self,
        value: Option<Vec<crate::com_atproto::repo::strong_ref::StrongRef<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `coordinateUncertaintyInMeters` field (optional)
    pub fn coordinate_uncertainty_in_meters(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `coordinateUncertaintyInMeters` field to an Option value (optional)
    pub fn maybe_coordinate_uncertainty_in_meters(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `decimalLatitude` field (optional)
    pub fn decimal_latitude(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `decimalLatitude` field to an Option value (optional)
    pub fn maybe_decimal_latitude(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `decimalLongitude` field (optional)
    pub fn decimal_longitude(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.3 = value.into();
        self
    }
    /// Set the `decimalLongitude` field to an Option value (optional)
    pub fn maybe_decimal_longitude(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.3 = value;
        self
    }
}

impl<'a, S: occurrence_state::State> OccurrenceBuilder<'a, S> {
    /// Set the `eventDate` field (optional)
    pub fn event_date(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Datetime>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `eventDate` field to an Option value (optional)
    pub fn maybe_event_date(
        mut self,
        value: Option<jacquard_common::types::string::Datetime>,
    ) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S> OccurrenceBuilder<'a, S>
where
    S: occurrence_state::State,
{
    /// Build the final struct
    pub fn build(self) -> Occurrence<'a> {
        Occurrence {
            associated_media: self.__unsafe_private_named.0,
            coordinate_uncertainty_in_meters: self.__unsafe_private_named.1,
            decimal_latitude: self.__unsafe_private_named.2,
            decimal_longitude: self.__unsafe_private_named.3,
            event_date: self.__unsafe_private_named.4,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Occurrence<'a> {
        Occurrence {
            associated_media: self.__unsafe_private_named.0,
            coordinate_uncertainty_in_meters: self.__unsafe_private_named.1,
            decimal_latitude: self.__unsafe_private_named.2,
            decimal_longitude: self.__unsafe_private_named.3,
            event_date: self.__unsafe_private_named.4,
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Occurrence<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, OccurrenceRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, jacquard_derive::IntoStatic,
)]
#[serde(rename_all = "camelCase")]
pub struct OccurrenceGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Occurrence<'a>,
}

impl From<OccurrenceGetRecordOutput<'_>> for Occurrence<'_> {
    fn from(output: OccurrenceGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Occurrence<'_> {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    type Record = OccurrenceRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct OccurrenceRecord;
impl jacquard_common::xrpc::XrpcResp for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = OccurrenceGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.occurrence";
    type Record = OccurrenceRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Occurrence<'a> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.occurrence"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_occurrence()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        if let Some(ref value) = self.associated_media {
            #[allow(unused_comparisons)]
            if value.len() > 10usize {
                return Err(::jacquard_lexicon::validation::ConstraintError::MaxLength {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "associated_media",
                    ),
                    max: 10usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.coordinate_uncertainty_in_meters {
            if *value < 0i64 {
                return Err(::jacquard_lexicon::validation::ConstraintError::Minimum {
                    path: ::jacquard_lexicon::validation::ValidationPath::from_field(
                        "coordinate_uncertainty_in_meters",
                    ),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

fn lexicon_doc_bio_lexicons_temp_occurrence() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("bio.lexicons.temp.occurrence"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.",
                        ),
                    ),
                    key: Some(::jacquard_common::CowStr::new_static("tid")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: None,
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "associatedMedia",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Array(::jacquard_lexicon::lexicon::LexArray {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Strong references to media records documenting the observation (Darwin Core dwc:associatedMedia).",
                                        ),
                                    ),
                                    items: ::jacquard_lexicon::lexicon::LexArrayItem::Ref(::jacquard_lexicon::lexicon::LexRef {
                                        description: None,
                                        r#ref: ::jacquard_common::CowStr::new_static(
                                            "com.atproto.repo.strongRef",
                                        ),
                                    }),
                                    min_length: None,
                                    max_length: Some(10usize),
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "coordinateUncertaintyInMeters",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                    description: None,
                                    default: None,
                                    minimum: Some(0i64),
                                    maximum: None,
                                    r#enum: None,
                                    r#const: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "decimalLatitude",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "decimalLongitude",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "eventDate",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The date-time when the observation occurred, in ISO 8601 format (Darwin Core dwc:eventDate).",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}
