// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.v0-1.occurrence
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, UriValue};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::com_atproto::repo::strong_ref::StrongRef;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "bio.lexicons.temp.v0-1.occurrence",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Occurrence<S: BosStr = DefaultStr> {
    ///Identification accepted by the occurrence user as the source of taxonID. Must be accompanied by taxonID. Indirectly maps to Darwin Core dwc:isAcceptedIdentification.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted_identification_id: Option<StrongRef<S>>,
    ///The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location (Darwin Core dwc:coordinateUncertaintyInMeters).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub coordinate_uncertainty_in_meters: Option<i64>,
    ///The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decimal_latitude: Option<S>,
    ///The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decimal_longitude: Option<S>,
    ///The date, date-time, or interval during which the dwc:Event occurred (Darwin Core dwc:eventDate). Recommended best practice is to use a value that conforms to ISO 8601-1:2019 for single dates or date-times, or to ISO 8601-2:2019 (EDTF) for intervals and dates of reduced or uncertain precision; separate the start and end of an interval with a solidus ("/"). Include timezone information whenever a time of day is given. Examples: "1963-03-08", "1971", "1906-06", "1963-03-08T14:07:00-06:00", "1995-05-21/1995-05-23".
    #[serde(skip_serializing_if = "Option::is_none")]
    pub event_date: Option<S>,
    ///Strong references to media records documenting the observation. Conceptually maps to the DwC-DP Occurrence Media table (https://gbif.github.io/dwc-dp/qrg/#Occurrence%20Media), which replaced the legacy dwc:associatedMedia term.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub media: Option<Vec<StrongRef<S>>>,
    ///The quantity of the organism present at the time of the Occurrence. Generally an integer or float but may be categorical, e.g. 'many' or '10-100' (Darwin Core dwc:organismQuantity).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organism_quantity: Option<S>,
    ///The type of quantification system used for the quantity of organisms (Darwin Core dwc:organismQuantityType).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub organism_quantity_type: Option<OccurrenceOrganismQuantityType<S>>,
    ///Identified taxon the occurrence user has accepted, preferably a stable URI (e.g. a GBIF species URI). Derived from identification specified by acceptedIdentificationID. Must be accompanied by acceptedIdentificationID. Represents a more specific version of the DarwinCore equivalent (Darwin Core dwc:taxonID).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub taxon_id: Option<UriValue<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// The type of quantification system used for the quantity of organisms (Darwin Core dwc:organismQuantityType).

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum OccurrenceOrganismQuantityType<S: BosStr = DefaultStr> {
    Individuals,
    PercentCover,
    Other(S),
}

impl<S: BosStr> OccurrenceOrganismQuantityType<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Individuals => "individuals",
            Self::PercentCover => "percent-cover",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "individuals" => Self::Individuals,
            "percent-cover" => Self::PercentCover,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for OccurrenceOrganismQuantityType<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for OccurrenceOrganismQuantityType<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for OccurrenceOrganismQuantityType<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for OccurrenceOrganismQuantityType<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for OccurrenceOrganismQuantityType<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for OccurrenceOrganismQuantityType<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = OccurrenceOrganismQuantityType<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            OccurrenceOrganismQuantityType::Individuals => {
                OccurrenceOrganismQuantityType::Individuals
            }
            OccurrenceOrganismQuantityType::PercentCover => {
                OccurrenceOrganismQuantityType::PercentCover
            }
            OccurrenceOrganismQuantityType::Other(v) => {
                OccurrenceOrganismQuantityType::Other(v.into_static())
            }
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct OccurrenceGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Occurrence<S>,
}

impl<S: BosStr> Occurrence<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, OccurrenceRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct OccurrenceRecord;
impl XrpcResp for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.occurrence";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = OccurrenceGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<OccurrenceGetRecordOutput<S>> for Occurrence<S> {
    fn from(output: OccurrenceGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Occurrence<S> {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.occurrence";
    type Record = OccurrenceRecord;
}

impl Collection for OccurrenceRecord {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.occurrence";
    type Record = OccurrenceRecord;
}

impl<S: BosStr> LexiconSchema for Occurrence<S> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.v0-1.occurrence"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_v0_1_occurrence()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.coordinate_uncertainty_in_meters {
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("coordinate_uncertainty_in_meters"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        if let Some(ref value) = self.media {
            #[allow(unused_comparisons)]
            if value.len() > 10usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("media"),
                    max: 10usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

pub mod occurrence_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type.
pub struct OccurrenceBuilder<St: occurrence_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<StrongRef<S>>,
        Option<i64>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<Vec<StrongRef<S>>>,
        Option<S>,
        Option<OccurrenceOrganismQuantityType<S>>,
        Option<UriValue<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Occurrence<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> OccurrenceBuilder<occurrence_state::Empty, DefaultStr> {
        OccurrenceBuilder::new()
    }
}

impl<S: BosStr> Occurrence<S> {
    /// Create a new builder for this type
    pub fn builder() -> OccurrenceBuilder<occurrence_state::Empty, S> {
        OccurrenceBuilder::builder()
    }
}

impl OccurrenceBuilder<occurrence_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        OccurrenceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> OccurrenceBuilder<occurrence_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        OccurrenceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `acceptedIdentificationID` field (optional)
    pub fn accepted_identification_id(mut self, value: impl Into<Option<StrongRef<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `acceptedIdentificationID` field to an Option value (optional)
    pub fn maybe_accepted_identification_id(mut self, value: Option<StrongRef<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `coordinateUncertaintyInMeters` field (optional)
    pub fn coordinate_uncertainty_in_meters(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `coordinateUncertaintyInMeters` field to an Option value (optional)
    pub fn maybe_coordinate_uncertainty_in_meters(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `decimalLatitude` field (optional)
    pub fn decimal_latitude(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `decimalLatitude` field to an Option value (optional)
    pub fn maybe_decimal_latitude(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `decimalLongitude` field (optional)
    pub fn decimal_longitude(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `decimalLongitude` field to an Option value (optional)
    pub fn maybe_decimal_longitude(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `eventDate` field (optional)
    pub fn event_date(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `eventDate` field to an Option value (optional)
    pub fn maybe_event_date(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `media` field (optional)
    pub fn media(mut self, value: impl Into<Option<Vec<StrongRef<S>>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `media` field to an Option value (optional)
    pub fn maybe_media(mut self, value: Option<Vec<StrongRef<S>>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `organismQuantity` field (optional)
    pub fn organism_quantity(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `organismQuantity` field to an Option value (optional)
    pub fn maybe_organism_quantity(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `organismQuantityType` field (optional)
    pub fn organism_quantity_type(
        mut self,
        value: impl Into<Option<OccurrenceOrganismQuantityType<S>>>,
    ) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `organismQuantityType` field to an Option value (optional)
    pub fn maybe_organism_quantity_type(
        mut self,
        value: Option<OccurrenceOrganismQuantityType<S>>,
    ) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<St: occurrence_state::State, S: BosStr> OccurrenceBuilder<St, S> {
    /// Set the `taxonID` field (optional)
    pub fn taxon_id(mut self, value: impl Into<Option<UriValue<S>>>) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `taxonID` field to an Option value (optional)
    pub fn maybe_taxon_id(mut self, value: Option<UriValue<S>>) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<St, S: BosStr> OccurrenceBuilder<St, S>
where
    St: occurrence_state::State,
{
    /// Build the final struct.
    pub fn build(self) -> Occurrence<S> {
        Occurrence {
            accepted_identification_id: self._fields.0,
            coordinate_uncertainty_in_meters: self._fields.1,
            decimal_latitude: self._fields.2,
            decimal_longitude: self._fields.3,
            event_date: self._fields.4,
            media: self._fields.5,
            organism_quantity: self._fields.6,
            organism_quantity_type: self._fields.7,
            taxon_id: self._fields.8,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Occurrence<S> {
        Occurrence {
            accepted_identification_id: self._fields.0,
            coordinate_uncertainty_in_meters: self._fields.1,
            decimal_latitude: self._fields.2,
            decimal_longitude: self._fields.3,
            event_date: self._fields.4,
            media: self._fields.5,
            organism_quantity: self._fields.6,
            organism_quantity_type: self._fields.7,
            taxon_id: self._fields.8,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_bio_lexicons_temp_v0_1_occurrence() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("bio.lexicons.temp.v0-1.occurrence"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A biodiversity observation record following Darwin Core standards. Represents a single occurrence of an organism.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("acceptedIdentificationID"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("coordinateUncertaintyInMeters"),
                                LexObjectProperty::Integer(LexInteger {
                                    minimum: Some(0i64),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("decimalLatitude"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The geographic latitude in decimal degrees (Darwin Core dwc:decimalLatitude). Valid range: -90 to 90.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("decimalLongitude"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The geographic longitude in decimal degrees (Darwin Core dwc:decimalLongitude). Valid range: -180 to 180.",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("eventDate"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The date, date-time, or interval during which the dwc:Event occurred (Darwin Core dwc:eventDate). Recommended best practice is to use a value that conforms to ISO 8601-1:2019 for single dates or date-times, or to ISO 8601-2:2019 (EDTF) for intervals and dates of reduced or uncertain precision; separate the start and end of an interval with a solidus (\"/\"). Include timezone information whenever a time of day is given. Examples: \"1963-03-08\", \"1971\", \"1906-06\", \"1963-03-08T14:07:00-06:00\", \"1995-05-21/1995-05-23\".",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("media"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Strong references to media records documenting the observation. Conceptually maps to the DwC-DP Occurrence Media table (https://gbif.github.io/dwc-dp/qrg/#Occurrence%20Media), which replaced the legacy dwc:associatedMedia term.",
                                        ),
                                    ),
                                    items: LexArrayItem::Ref(LexRef {
                                        r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                        ..Default::default()
                                    }),
                                    max_length: Some(10usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("organismQuantity"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The quantity of the organism present at the time of the Occurrence. Generally an integer or float but may be categorical, e.g. 'many' or '10-100' (Darwin Core dwc:organismQuantity).",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("organismQuantityType"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The type of quantification system used for the quantity of organisms (Darwin Core dwc:organismQuantityType).",
                                        ),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("taxonID"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Identified taxon the occurrence user has accepted, preferably a stable URI (e.g. a GBIF species URI). Derived from identification specified by acceptedIdentificationID. Must be accompanied by acceptedIdentificationID. Represents a more specific version of the DarwinCore equivalent (Darwin Core dwc:taxonID).",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Uri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
