// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: bio.lexicons.temp.v0-1.remark
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{lexicon, IntoStatic};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// Free text that fills a Darwin Core remarks term on another record, such as dwc:occurrenceRemarks on an occurrence. Kept in its own record so authored prose, a potential creative work, can be attributed and licensed separately from the facts in the record it describes. The record it describes points to it with an AT-URI field named for the term (e.g. occurrence.occurrenceRemarksID), and that forward reference is authoritative: a remark nothing references fills no term. Not for discussion or replies.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "bio.lexicons.temp.v0-1.remark",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Remark<S: BosStr = DefaultStr> {
    ///The text of the remark. Becomes the value of dwcTerm when the subject is exported to Darwin Core.
    pub body: S,
    ///The Darwin Core term this remark fills on its subject. Should correspond to the field that references this remark, e.g. occurrenceRemarks for occurrence.occurrenceRemarksID.
    pub dwc_term: RemarkDwcTerm<S>,
    ///URI of the license under which this text is published (Dublin Core dcterms:license). Creative Commons license URIs are the recommended values.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<RemarkLicense<S>>,
    ///AT-URI of the record this remark describes, which should be the record whose forward reference points here. Lets the remark be understood and indexed on its own, and lets consumers detect a forward reference that points at the wrong remark.
    pub subject: AtUri<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// The Darwin Core term this remark fills on its subject. Should correspond to the field that references this remark, e.g. occurrenceRemarks for occurrence.occurrenceRemarksID.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RemarkDwcTerm<S: BosStr = DefaultStr> {
    OccurrenceRemarks,
    EventRemarks,
    IdentificationRemarks,
    Other(S),
}

impl<S: BosStr> RemarkDwcTerm<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::OccurrenceRemarks => "occurrenceRemarks",
            Self::EventRemarks => "eventRemarks",
            Self::IdentificationRemarks => "identificationRemarks",
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "occurrenceRemarks" => Self::OccurrenceRemarks,
            "eventRemarks" => Self::EventRemarks,
            "identificationRemarks" => Self::IdentificationRemarks,
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for RemarkDwcTerm<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for RemarkDwcTerm<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for RemarkDwcTerm<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for RemarkDwcTerm<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for RemarkDwcTerm<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for RemarkDwcTerm<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = RemarkDwcTerm<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            RemarkDwcTerm::OccurrenceRemarks => RemarkDwcTerm::OccurrenceRemarks,
            RemarkDwcTerm::EventRemarks => RemarkDwcTerm::EventRemarks,
            RemarkDwcTerm::IdentificationRemarks => RemarkDwcTerm::IdentificationRemarks,
            RemarkDwcTerm::Other(v) => RemarkDwcTerm::Other(v.into_static()),
        }
    }
}

/// URI of the license under which this text is published (Dublin Core dcterms:license). Creative Commons license URIs are the recommended values.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RemarkLicense<S: BosStr = DefaultStr> {
    HttpsCreativecommonsOrgPublicdomainZero10,
    HttpsCreativecommonsOrgLicensesBy40,
    HttpsCreativecommonsOrgLicensesByNc40,
    HttpsCreativecommonsOrgLicensesBySa40,
    HttpsCreativecommonsOrgLicensesByNcSa40,
    Other(S),
}

impl<S: BosStr> RemarkLicense<S> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::HttpsCreativecommonsOrgPublicdomainZero10 => {
                "https://creativecommons.org/publicdomain/zero/1.0/"
            }
            Self::HttpsCreativecommonsOrgLicensesBy40 => {
                "https://creativecommons.org/licenses/by/4.0/"
            }
            Self::HttpsCreativecommonsOrgLicensesByNc40 => {
                "https://creativecommons.org/licenses/by-nc/4.0/"
            }
            Self::HttpsCreativecommonsOrgLicensesBySa40 => {
                "https://creativecommons.org/licenses/by-sa/4.0/"
            }
            Self::HttpsCreativecommonsOrgLicensesByNcSa40 => {
                "https://creativecommons.org/licenses/by-nc-sa/4.0/"
            }
            Self::Other(s) => s.as_ref(),
        }
    }
    /// Construct from a string-like value, matching known values.
    pub fn from_value(s: S) -> Self {
        match s.as_ref() {
            "https://creativecommons.org/publicdomain/zero/1.0/" => {
                Self::HttpsCreativecommonsOrgPublicdomainZero10
            }
            "https://creativecommons.org/licenses/by/4.0/" => {
                Self::HttpsCreativecommonsOrgLicensesBy40
            }
            "https://creativecommons.org/licenses/by-nc/4.0/" => {
                Self::HttpsCreativecommonsOrgLicensesByNc40
            }
            "https://creativecommons.org/licenses/by-sa/4.0/" => {
                Self::HttpsCreativecommonsOrgLicensesBySa40
            }
            "https://creativecommons.org/licenses/by-nc-sa/4.0/" => {
                Self::HttpsCreativecommonsOrgLicensesByNcSa40
            }
            _ => Self::Other(s),
        }
    }
}

impl<S: BosStr> core::fmt::Display for RemarkLicense<S> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<S: BosStr> AsRef<str> for RemarkLicense<S> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<S: BosStr> Serialize for RemarkLicense<S> {
    fn serialize<Ser>(&self, serializer: Ser) -> Result<Ser::Ok, Ser::Error>
    where
        Ser: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, S: Deserialize<'de> + BosStr> Deserialize<'de> for RemarkLicense<S> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = S::deserialize(deserializer)?;
        Ok(Self::from_value(s))
    }
}

impl<S: BosStr + Default> Default for RemarkLicense<S> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl<S: BosStr> jacquard_common::IntoStatic for RemarkLicense<S>
where
    S: BosStr + jacquard_common::IntoStatic,
    S::Output: BosStr,
{
    type Output = RemarkLicense<S::Output>;
    fn into_static(self) -> Self::Output {
        match self {
            RemarkLicense::HttpsCreativecommonsOrgPublicdomainZero10 => {
                RemarkLicense::HttpsCreativecommonsOrgPublicdomainZero10
            }
            RemarkLicense::HttpsCreativecommonsOrgLicensesBy40 => {
                RemarkLicense::HttpsCreativecommonsOrgLicensesBy40
            }
            RemarkLicense::HttpsCreativecommonsOrgLicensesByNc40 => {
                RemarkLicense::HttpsCreativecommonsOrgLicensesByNc40
            }
            RemarkLicense::HttpsCreativecommonsOrgLicensesBySa40 => {
                RemarkLicense::HttpsCreativecommonsOrgLicensesBySa40
            }
            RemarkLicense::HttpsCreativecommonsOrgLicensesByNcSa40 => {
                RemarkLicense::HttpsCreativecommonsOrgLicensesByNcSa40
            }
            RemarkLicense::Other(v) => RemarkLicense::Other(v.into_static()),
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RemarkGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Remark<S>,
}

impl<S: BosStr> Remark<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, RemarkRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct RemarkRecord;
impl XrpcResp for RemarkRecord {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.remark";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = RemarkGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<RemarkGetRecordOutput<S>> for Remark<S> {
    fn from(output: RemarkGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Remark<S> {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.remark";
    type Record = RemarkRecord;
}

impl Collection for RemarkRecord {
    const NSID: &'static str = "bio.lexicons.temp.v0-1.remark";
    type Record = RemarkRecord;
}

impl<S: BosStr> LexiconSchema for Remark<S> {
    fn nsid() -> &'static str {
        "bio.lexicons.temp.v0-1.remark"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_bio_lexicons_temp_v0_1_remark()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.body;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 3000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("body"),
                    max: 3000usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.dwc_term;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 128usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("dwc_term"),
                    max: 128usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        if let Some(ref value) = self.license {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 128usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("license"),
                    max: 128usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod remark_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Body;
        type DwcTerm;
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Body = Unset;
        type DwcTerm = Unset;
        type Subject = Unset;
    }
    ///State transition - sets the `body` field to Set
    pub struct SetBody<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetBody<St> {}
    impl<St: State> State for SetBody<St> {
        type Body = Set<members::body>;
        type DwcTerm = St::DwcTerm;
        type Subject = St::Subject;
    }
    ///State transition - sets the `dwc_term` field to Set
    pub struct SetDwcTerm<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDwcTerm<St> {}
    impl<St: State> State for SetDwcTerm<St> {
        type Body = St::Body;
        type DwcTerm = Set<members::dwc_term>;
        type Subject = St::Subject;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubject<St> {}
    impl<St: State> State for SetSubject<St> {
        type Body = St::Body;
        type DwcTerm = St::DwcTerm;
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `body` field
        pub struct body(());
        ///Marker type for the `dwc_term` field
        pub struct dwc_term(());
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type.
pub struct RemarkBuilder<St: remark_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<RemarkDwcTerm<S>>,
        Option<RemarkLicense<S>>,
        Option<AtUri<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Remark<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> RemarkBuilder<remark_state::Empty, DefaultStr> {
        RemarkBuilder::new()
    }
}

impl<S: BosStr> Remark<S> {
    /// Create a new builder for this type
    pub fn builder() -> RemarkBuilder<remark_state::Empty, S> {
        RemarkBuilder::builder()
    }
}

impl RemarkBuilder<remark_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        RemarkBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> RemarkBuilder<remark_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        RemarkBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RemarkBuilder<St, S>
where
    St: remark_state::State,
    St::Body: remark_state::IsUnset,
{
    /// Set the `body` field (required)
    pub fn body(mut self, value: impl Into<S>) -> RemarkBuilder<remark_state::SetBody<St>, S> {
        self._fields.0 = Option::Some(value.into());
        RemarkBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RemarkBuilder<St, S>
where
    St: remark_state::State,
    St::DwcTerm: remark_state::IsUnset,
{
    /// Set the `dwcTerm` field (required)
    pub fn dwc_term(
        mut self,
        value: impl Into<RemarkDwcTerm<S>>,
    ) -> RemarkBuilder<remark_state::SetDwcTerm<St>, S> {
        self._fields.1 = Option::Some(value.into());
        RemarkBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: remark_state::State, S: BosStr> RemarkBuilder<St, S> {
    /// Set the `license` field (optional)
    pub fn license(mut self, value: impl Into<Option<RemarkLicense<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `license` field to an Option value (optional)
    pub fn maybe_license(mut self, value: Option<RemarkLicense<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> RemarkBuilder<St, S>
where
    St: remark_state::State,
    St::Subject: remark_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> RemarkBuilder<remark_state::SetSubject<St>, S> {
        self._fields.3 = Option::Some(value.into());
        RemarkBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RemarkBuilder<St, S>
where
    St: remark_state::State,
    St::Body: remark_state::IsSet,
    St::DwcTerm: remark_state::IsSet,
    St::Subject: remark_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Remark<S> {
        Remark {
            body: self._fields.0.unwrap(),
            dwc_term: self._fields.1.unwrap(),
            license: self._fields.2,
            subject: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Remark<S> {
        Remark {
            body: self._fields.0.unwrap(),
            dwc_term: self._fields.1.unwrap(),
            license: self._fields.2,
            subject: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_bio_lexicons_temp_v0_1_remark() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{deps::smol_str::SmolStr, types::blob::MimeType, CowStr};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("bio.lexicons.temp.v0-1.remark"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "Free text that fills a Darwin Core remarks term on another record, such as dwc:occurrenceRemarks on an occurrence. Kept in its own record so authored prose, a potential creative work, can be attributed and licensed separately from the facts in the record it describes. The record it describes points to it with an AT-URI field named for the term (e.g. occurrence.occurrenceRemarksID), and that forward reference is authoritative: a remark nothing references fills no term. Not for discussion or replies.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("subject"),
                                SmolStr::new_static("dwcTerm"), SmolStr::new_static("body")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("body"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The text of the remark. Becomes the value of dwcTerm when the subject is exported to Darwin Core.",
                                        ),
                                    ),
                                    max_length: Some(3000usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("dwcTerm"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "The Darwin Core term this remark fills on its subject. Should correspond to the field that references this remark, e.g. occurrenceRemarks for occurrence.occurrenceRemarksID.",
                                        ),
                                    ),
                                    max_length: Some(128usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("license"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "URI of the license under which this text is published (Dublin Core dcterms:license). Creative Commons license URIs are the recommended values.",
                                        ),
                                    ),
                                    max_length: Some(128usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("subject"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "AT-URI of the record this remark describes, which should be the record whose forward reference points here. Lets the remark be understood and indexed on its own, and lets consumers detect a forward reference that points at the wrong remark.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
